/* data_events.js · 事件库（DL_RS_4.158 自单文件拆分，勿改结构） */
let EVENTS = [
  /* ==== 幼年（band 0，品质混杂：白/绿/蓝） ==== */ // XL_RS 4.66：原注释误写"白(common)"，块内含绿品(启蒙道院)与蓝品(偷学秘籍)
  {band:0, q:'uncommon', minAge:7, name:'启蒙道院', text:'觉醒当日，你被送进启蒙道院。青石操场上，同龄人的灵根次第绽放——兽吼阵阵、器鸣铮铮，衬得你渺小如尘，却也燃起一簇不甘的火焰。',
   opts:[{label:'刻苦修习', need:{attr:{悟性:12}}, eff:{悟性:4}}, {label:'广交朋友', eff:{力量:2,灵动:2}}]},
  {band:0, q:'common', minAge:8, name:'天赋测试', text:'太玄圣宗测修士驾临小镇，水晶球在孩童掌心次第亮起微光。轮到你时，他多看了你一眼——那一眼里，藏着天壤之别的两种未来。',
   opts:[{label:'接受测试', need:{attr:{气运:12}},
 eff:{声望:4}}, {label:'躲在家里', eff:{}}]},
      {band:0, q:'common', minAge:7, name:'溪畔摸鱼', text:'盛夏溪水清凉，你卷起裤腿下河摸鱼。', opts:[{label:'下水摸鱼',eff:{气血:2,神识:1}},{label:'岸边观望',eff:{悟性:1}}]},
{band:0, q:'common', minAge:9, name:'被欺负', text:'贵族子弟围着你指指点点，嘲笑你家贫、灵根平庸，为首那人抬手便将你推了个趔趄，胸中那口火再也压不住。',
   opts:[{label:'忍气吞声', eff:{悟性:2}}, {label:'奋起反抗', need:{attr:{力量:12}}, roll:{chance:0.45, succ:{力量:5,声望:4}, succText:'你打回去了，虽然鼻青脸肿，心里却痛快。', fail:{气血:-4}, failText:'你被揍得更惨，还被嘲笑了一番。'}}]},
  {band:0, q:'rare', minAge:10, name:'偷学秘籍', syn:{cat:'wu',catMult:1.25}, text:'你偶然发现一本泛黄的修炼手札，字迹潦草，似有玄机。',
   opts:[{label:'潜心研读', need:{attr:{悟性:15}}, roll:{chance:0.6, succ:{悟性:6}, succText:'手札里是一套吐纳法，你悟性大增。', fail:{悟性:-2}, failText:'强行修炼，险些岔了气。'}}, {label:'上交给长辈', eff:{家境:2}}]},
  {band:0, q:'common', minAge:10, name:'大病一场', text:'入冬的第一场雪里，你烧得神志不清、浑身滚烫，母亲守在床边熬了三天三夜的药，铜钱大的家底转眼见了底。',
   opts:[{label:'倾家求医', eff:{家境:-4, 气血:4}}, {label:'硬扛过去', need:{attr:{气血:12}}, roll:{chance:0.5, succ:{气血:3}, succText:'命硬，你挺过来了。', fail:{气血:-8}, failText:'病情缠绵，落了病根。'}}]},
  {band:0, q:'uncommon', minAge:12, name:'学院比试', text:'学院年度比试开擂，少年们摩拳擦掌——拔得头筹者，宗门会亲自下场挑选。',
   opts:[{label:'报名参加', need:{attr:{力量:10}}, roll:{chance:0.55, succ:{声望:6,力量:4}, succText:'你击败数名同龄人，一战成名。', fail:{}, failText:'第一轮就败下阵来。'}}, {label:'专心修炼', eff:{悟性:3}}]},
  /* ==== 白 · 青年 ==== */
  {band:1, q:'uncommon', minAge:16, name:'偶遇仙草', syn:{cat:'zhi',catMult:1.25}, text:'雨后山涧，溪石缝里一株仙草正吐纳霞光，叶脉流转如活物——正是炼丹师梦寐以求的灵植，只是扎根处隐隐透着危险的气息。',
   opts:[{label:'当场服下', need:{attr:{气血:20}}, eff:{气血:8, 悟性:2}}, {label:'采摘出售', eff:{灵石:400}}]},
  {band:1, q:'uncommon', minAge:17, name:'太玄圣宗招揽', text:'太玄圣宗使者登门，锦衣华服、态度倨傲，却许诺你享用不尽的修炼资源与供奉之位。', ex:'wuhundian', req:{lv:20, notOrg:true},
   opts:[{label:'加入太玄圣宗', need:{lv:20}, eff:{家境:8, 声望:6}}, {label:'婉言谢绝', eff:{悟性:2}}]},
  {band:1, q:'rare', minAge:20, name:'玄元古墓', syn:{cat:'wu',catMult:1.25}, text:'一处古墓中，你发现一枚刻"玄"字的青铜古令，隐有龙吟，似与上古宗门有关。', once:true, ling:'玄令', w:0.45, // XL_RS 4.38：势力功法专属化——元始宗六艺仅藏经阁可习得，玄元古墓只余乾坤六令信物
   opts:[{label:'收入怀中', eff:{悟性:4}}]}, // 信物只记令，不再开功法链
  {band:1, q:'rare', minAge:22, name:'灵宝机缘', syn:{cat:'wu',catMult:1.25}, text:'拍卖会上出现一件上古灵宝，据说蕴含大机缘。',
   opts:[{label:'倾囊竞拍', need:{money:700}, eff:{灵石:-700, 气血:3, 悟性:1}}, {label:'放弃', eff:{}}]},
  {band:1, q:'common', minAge:24, name:'同门相争', text:'你在宗门崭露头角后，同门师兄的眼神悄然变了味——好资源总被人捷足先登，暗处传来不怀好意的低语。', req:{hasOrg:true},
   opts:[{label:'据理力争', need:{attr:{力量:25}},
 roll:{chance:0.55, succ:{声望:6}, succText:'你证明了自己，对方哑口无言。', fail:{}, failText:'反而被排挤，处处受气。'}}, {label:'退让一步', eff:{悟性:2}}]},
      {band:1, q:'common', minAge:14, name:'街市帮工', text:'你在集市帮人搬运货物，换几枚铜板。', opts:[{label:'勤快帮工',eff:{灵石:40,气血:1}},{label:'躲懒歇脚',eff:{}}]},
{band:1, q:'common', minAge:28, name:'瓶颈顿悟', text:'修为积攒到临界，却像撞上一堵无形的墙，任你苦修多年，纹丝不动。越是心急，那墙便越厚重。',
   opts:[{label:'入世历练', eff:{悟性:4, 力量:3}}, {label:'死磕闭关', need:{attr:{悟性:25}}, roll:{chance:0.4, succ:{悟性:5}, succText:'闭关三年，一朝顿悟。', fail:{}, failText:'越急越乱，毫无进展。'}}]},
  /* ==== 白 · 中年 / 老年 ==== */
  {band:2, q:'rare', minAge:32, name:'建宗立派', text:'功成名就的你，动了开宗立派的念头——以一己之力创立宗门，自此宗主之尊，自由度高，全方面发展。', req:{lv:70, money:1000, minQuality:'ding', notOrg:true},
   opts:[{label:'开宗立派', eff:{家境:-10, 声望:20}, joinOrg:'自建宗门'}, {label:'独善其身', eff:{悟性:3}}]},
  {band:2, q:'uncommon', minAge:35, name:'收徒传道', text:'有少年慕名而来，跪求拜师。', req:{prestige:10, minQuality:'pu', lv:30},
   opts:[{label:'收下弟子', need:{attr:{悟性:18}}, eff:{悟性:3, 声望:5}}, {label:'婉拒', eff:{}}]},
  {band:2, q:'uncommon', minAge:45, name:'突破之机', text:'修为在丹田翻涌，你隐约触碰到下一境界的门槛，只差临门一脚——却怎么也迈不过去。',
   opts:[{label:'寻求名师指点', eff:{悟性:5, 家境:-2}}, {label:'自行感悟', need:{attr:{悟性:22}}, roll:{chance:0.4, succ:{悟性:6}, succText:'一朝明悟，境界松动了。', fail:{}, failText:'依旧无果。'}}]},
  {band:2, q:'common', minAge:50, name:'子女成长', text:'孩子拉着你的衣角，眼睛亮晶晶地问：「爹爹，我也想觉醒灵根，走修士之路！」', req:{hasChild:true},
   opts:[{label:'倾力培养', need:{money:200},
 eff:{家境:-4, 悟性:4}}, {label:'顺其自然', eff:{}}]},
      {band:2, q:'common', minAge:33, name:'山中采药', text:'你入深山采药，辨得几味珍稀药草。', opts:[{label:'细心采摘',eff:{悟性:2,灵石:60}},{label:'浅尝辄止',eff:{气血:1}}]},
{band:1, q:'rare', minAge:22, name:'子女病重', text:'一场时疫席卷小镇，你的孩子不幸染病，命悬一线。', req:{hasChild:true}, once:true, w:0.3,
   opts:[{label:'遍寻良医', need:{money:300}, roll:{chance:0.6, extra:0.05, succ:{}, succText:'名医出手，孩子转危为安。', fail:{子嗣:-1, 家境:-6}, failText:'倾尽家财仍未能留住，你痛失一子。'}}, {label:'听天由命', roll:{chance:0.35, extra:0.05, succ:{}, succText:'孩子命硬，竟自己挺了过来。', fail:{子嗣:-1, 家境:-4}, failText:'未能留住孩子，白发人送黑发人。'}}]},
  {band:1, q:'rare', minAge:20, name:'子女觉醒', text:'你的孩子到了觉醒灵根的年纪，全家人的心都悬了起来。', req:{hasChild:true}, once:true, w:0.8,
   opts:[{label:'悉心引导', need:{attr:{悟性:25}}, roll:{chance:0.5, extra:0.05, succ:{悟性:2, 声望:4}, succText:'孩子竟觉醒了不错的天赋，家族后继有人。', fail:{悟性:1}, failText:'孩子天资平平，倒也安稳。'}}, {label:'顺其自然', eff:{悟性:1}}]},
  {band:2, q:'rare', minAge:40, maxAge:52, name:'老来得子', text:'多年膝下渐冷清，家中竟又传来喜讯。', req:{spouse:true}, once:true, w:0.3,
   opts:[{label:'喜添麟儿', eff:{子嗣:1, 家境:-3, 悟性:1}}, {label:'顺其自然', eff:{}}]},
  {band:3, q:'common', minAge:65, name:'回顾一生', text:'回首前尘，你忽然想通了很多事。',
   opts:[{label:'著书立说', need:{attr:{悟性:40}},
 eff:{悟性:5, 声望:4}}, {label:'传道于子', eff:{悟性:3}}]},
      {band:3, q:'common', minAge:60, name:'含饴弄孙', text:'孙辈绕膝，天伦之乐，岁月也温柔了几分。', opts:[{label:'含饴弄孙',eff:{神识:3,悟性:1}},{label:'闭门清修',eff:{悟性:2}}]},
{band:3, q:'common', minAge:75, name:'生死之间', text:'你感到大限将至，开始安排后事。', req:{lifeLeft:8},
   opts:[{label:'坦然面对', need:{attr:{悟性:35}}, eff:{悟性:4}}, {label:'执念难消', eff:{悟性:2}}]},
  /* ==== 蓝（rare） ==== */
  {band:0, q:'common', minAge:8, name:'村中猎妖', syn:{cat:'shou',catMult:1.25}, text:'长辈带你去猎妖森林外围见世面，忽然撞见一头妖兽。',
   opts:[{label:'上前试探', need:{attr:{灵动:12}}, roll:{chance:0.5, succ:{力量:6,灵动:4}, succText:'你胆识过人，长辈们赞不绝口。', fail:{气血:-5}, failText:'妖兽暴起，你被拍飞，卧床月余。'}}, {label:'远远观望', eff:{悟性:4}}]},
  {band:0, q:'uncommon', minAge:10, name:'妖兽传闻', syn:{cat:'shou',catMult:1.25}, text:'镇上都在传，附近林子里出现了一头罕见的千年妖兽。',
   opts:[{label:'悄悄去寻', need:{attr:{力量:15}}, roll:{chance:0.25, extra:0.15, succ:{力量:8,声望:8}, succText:'你竟目睹了千年妖兽的真容，全身而退。', fail:{气血:-10}, failText:'险些丧命，被猎人救回。'}}, {label:'当没听见', eff:{}}]},
  {band:0, q:'uncommon', minAge:12, name:'星象垂青', text:'今夜星河璀璨，你仰观天象，竟隐隐窥见一丝命数轨迹。', w:0.7,
   opts:[{label:'静观星轨', need:{attr:{悟性:18}}, eff:{气运:4, 悟性:2}, evSet:'xingxiang'}, {label:'观星许愿', eff:{气运:2}}]},
  {band:1, q:'rare', minAge:14, name:'学院切磋赛', text:'附近几所学院联合举办切磋赛，各地天才齐聚。', req:{lv:20},
   opts:[{label:'报名参赛', need:{lv:20}, roll:{chance:0.5, extra:0.05, succ:{声望:12,力量:5,灵动:5}, succText:'你在大赛上大放异彩，名动一时。', fail:{气血:-6}, failText:'大赛残酷，你重伤退场。'}}, {label:'赛场观摩', eff:{悟性:6}}]},
  {band:1, q:'rare', minAge:15, name:'妖域引路', text:'你与同伴深入万妖山脉，为猎取妖兽内丹、磨砺修为做准备。一处岔路，仿佛在引你走向深处。', once:true, chainId:'xingdou', chainStart:true, step:'xingdou1', w:0.35,
   opts:[{label:'循路深入', eff:{力量:4, 神识:3}}]},
  {band:1, q:'uncommon', minAge:18, name:'生死仇杀', text:'你卷入一场宗门恩怨，仇家寻上门来。', req:{lv:20},
   opts:[{label:'正面迎战', need:{attr:{力量:30}}, evSet:'chousha', roll:{chance:0.45, extra:0.05, succ:{声望:10,力量:6}, succText:'你击杀来敌，威名更盛。', fail:{气血:-15}, failText:'寡不敌众，你身受重伤逃遁。', death:0.10, deathText:'惨死于仇家刀下'}}, {label:'避其锋芒', eff:{}}]},
  {band:1, q:'uncommon', minAge:26, name:'兽潮来袭', syn:{cat:'shou',catMult:1.25}, text:'落日森林妖兽暴动，冲向人类城镇。',
   opts:[{label:'上阵守城', need:{attr:{力量:25}}, evSet:'shouchao1', roll:{chance:0.5, extra:0.05, succ:{声望:12,力量:6,灵动:4}, succText:'你斩兽无数，被百姓奉为英雄。', fail:{气血:-12}, failText:'混战中身受重创。', death:0.07, deathText:'战死于兽潮'}}, {label:'随众撤离', eff:{}}]},
  {band:2, q:'rare', minAge:38, name:'旧敌复仇', text:'当年结下的仇家，如今已是渡劫期强者，前来复仇。', req:{ev:'chousha'},
   opts:[{label:'迎战宿敌', need:{attr:{力量:40}}, evSet:'jiudi', roll:{chance:0.4, extra:0.05, succ:{声望:14,力量:8}, succText:'你以弱胜强，斩杀宿敌。', fail:{气血:-18}, failText:'不敌，重伤垂死。', death:0.12, deathText:'死于宿敌之手'}}, {label:'远遁避祸', eff:{家境:-4}}]},
  {band:2, q:'rare', minAge:42, name:'妖兽暴动', syn:{cat:'shou',catMult:1.25}, text:'万妖山脉深处，一头高阶妖兽似乎苏醒了，兽潮滚滚。', req:{ev:'shouchao1'},
   opts:[{label:'挺身而出', need:{attr:{力量:50}}, evSet:'shouchao2', roll:{chance:0.35, extra:0.1, succ:{声望:18,力量:8}, succText:'你出手镇压兽潮，修仙界都记住了你的名字。', fail:{气血:-18}, failText:'几乎被兽潮吞没。', death:0.15, deathText:'葬身于兽潮'}}, {label:'固守不出', eff:{}}]},
  {band:2, q:'rare', minAge:55, name:'帝国相邀', text:'帝国皇室遣使相邀，许你供奉高位。', req:{lv:55, prestige:30, minQuality:'pu'},
   opts:[{label:'接受供奉', need:{prestige:30}, eff:{家境:10, 声望:5}}, {label:'婉拒归隐', eff:{悟性:4}}]},
  /* DL_RS_4.232：强者生活事件——60岁后替代白/绿生活流（合体起淘汰白、渡劫起淘汰绿），题材强者化 */
  {band:3, q:'rare', minAge:60, name:'闭关苦修', text:'你于洞府之中闭关参悟，不问世事。岁月流逝，你在寂静中窥见武道的更深层奥义。',
   opts:[{label:'闭关三载', eff:{悟性:5, 神识:4}, txt:'三载闭关，一朝出关——你的武道感悟愈发圆融。'}, {label:'静坐数月', eff:{悟性:3}, txt:'静坐感悟，心性愈发沉稳。'}]},
  {band:3, q:'rare', minAge:60, name:'问道论剑', text:'一位同阶强者慕名而来，与你以武论道，切磋印证。', req:{lv:60},
   opts:[{label:'全力论剑', need:{attr:{力量:60}}, roll:{chance:0.5, extra:0.06, succ:{声望:10, 力量:6, 悟性:3}, succText:'棋逢对手，你在论剑中窥见了自己武道的破绽与精进。', fail:{气血:-6}, failText:'论剑落败，你闭关反思。'}}, {label:'以茶论道', eff:{悟性:4}, txt:'不诉诸刀兵，仅以言语论道，亦有所得。'}]},
  {band:3, q:'rare', minAge:60, name:'踏遍山河', text:'你卸下俗务，踏遍修仙界山河，观沧海桑田、天地大势。',
   opts:[{label:'登临绝巅', eff:{悟性:5, 神识:3}, txt:'立于修仙界之巅俯瞰众生，天地辽阔，心亦辽阔。'}, {label:'行舟江海', eff:{气血:3, 神识:2}, txt:'江海涤荡心神，你与天地愈发亲近。'}]},
  {band:3, q:'rare', minAge:62, name:'品茗弈棋', text:'你与故友于庭院对弈品茗，谈笑间指点风云。',
   opts:[{label:'对弈三局', eff:{悟性:4, 神识:3}, txt:'棋局如人生，你在纵横之间明悟取舍之道。'}, {label:'闲谈往事', eff:{神识:3}, txt:'旧事重提，心绪渐平。'}]},
  {band:3, q:'rare', minAge:64, name:'秘境寻踪', text:'一处上古秘境现世，传闻其中有强者遗留的机缘。',
   opts:[{label:'入秘境一探', need:{attr:{气血:65}}, roll:{chance:0.4, extra:0.08, succ:{悟性:8, 神识:6, 气运:4}, succText:'你在秘境中寻得前人感悟，修为愈发精深。', fail:{气血:-12}, failText:'秘境凶险，你重伤而返。'}, shenPool:['紫雷真身','七杀剑诀','焚天火莲','万剑归宗','雷神怒','风神腿']}, {label:'敬而远之', eff:{悟性:3}, txt:'机缘与凶险并存，你选择稳健。'}]},
  {band:3, q:'rare', minAge:60, name:'坐镇一方', text:'你威名远播，一方百姓奉你为守护者，求你坐镇以镇邪祟。',
   opts:[{label:'应允坐镇', eff:{声望:12, 气运:3}, txt:'你坐镇一方，邪祟闻风远遁，万家安宁。'}, {label:'婉言谢绝', eff:{悟性:4}, txt:'你不愿受俗务羁绊，专心武道。'}]},
  {band:3, q:'rare', minAge:63, name:'观星悟道', text:'夜阑人静，你独上高楼观星，星象流转间似有天地法则隐现。',
   opts:[{label:'凝神观星', need:{attr:{悟性:55}}, roll:{chance:0.45, extra:0.06, succ:{悟性:8, 气运:4}, succText:'星象与你心神共鸣，你对天地法则有了新的领悟。', fail:{神识:-6}, failText:'星象太过玄奥，你心神微倦。'}}, {label:'凭栏赏月', eff:{神识:3}, txt:'月华如水，心境澄明。'}]},
  {band:3, q:'rare', minAge:65, name:'故人长谈', text:'多年不见的故人寻来，与你把酒言欢，共忆峥嵘岁月。',
   opts:[{label:'把酒言欢', eff:{神识:4, 悟性:3}, txt:'故人依旧，江湖已远。一番长谈，心中块垒尽消。'}, {label:'赠予机缘', eff:{声望:8, 气运:2}, txt:'你念及旧情，指点故人后辈一二。'}]},
  {band:3, q:'uncommon', minAge:60, name:'山巅独酌', text:'你携一壶酒登上山巅，对月独酌，俯瞰万家灯火。',
   opts:[{label:'独酌至天明', eff:{神识:3, 悟性:2}, txt:'山风拂面，酒入愁肠，心中却愈发清明。'}, {label:'静坐观云', eff:{悟性:3}, txt:'云卷云舒，宠辱不惊。'}]},
  {band:3, q:'uncommon', minAge:62, name:'讲学论道', text:'有学府与宗门慕名相邀，请你开坛讲学，传道解惑。',
   opts:[{label:'开坛三日', eff:{声望:8, 悟性:3}, txt:'你深入浅出，听者如痴如醉，桃李满天下。'}, {label:'携徒游历', eff:{悟性:3, 声望:4}, txt:'你带着几名后辈游历历练，教学相长。'}]},
  {band:3, q:'uncommon', minAge:60, name:'狩猎历练', syn:{cat:'shou',catMult:1.15}, text:'你带队深入万妖山脉，狩猎强大妖兽，磨砺身手。', req:{lv:60},
   opts:[{label:'猎取兽王', need:{attr:{力量:55}}, roll:{chance:0.45, extra:0.06, succ:{力量:6, 灵动:4, 声望:6}, succText:'你亲手猎杀兽王，威震一方。', fail:{气血:-10}, failText:'兽王凶猛，你负伤而归。'}}, {label:'围猎妖兽', eff:{力量:3, 灵动:2}, txt:'小有所获，身手不减当年。'}]},
  {band:3, q:'rare', minAge:60, name:'冲击极限', text:'寿元渐长，你想在最后的日子里冲击更高的境界。',
   opts:[{label:'放手一搏', need:{attr:{气血:30}}, roll:{chance:0.35, extra:0.05, succ:{悟性:8,力量:6}, succText:'你将毕生领悟融会贯通。', fail:{气血:-10}, failText:'气血亏空，大不如前。', death:0.06, deathText:'冲击境界时气血耗尽'}}, {label:'安心颐养', eff:{悟性:3}}]},
  {band:3, q:'epic', minAge:70, name:'最后的兽潮', once:true, syn:{cat:'shou',catMult:1.2}, text:'又一场百年不遇的兽潮袭来，你已垂垂老矣。', req:{ev:'shouchao1'},
   opts:[{label:'最后一次出手', need:{attr:{力量:40}}, evAdd:{flag:'shouchao2', eff:{声望:10}, txt:'你曾镇压过兽潮，此刻百姓视你为最后的希望'}, roll:{chance:0.3, extra:0.1, succ:{声望:20,力量:6}, succText:'你以残躯护住一城百姓，被载入史册。', fail:{气血:-20}, failText:'力不从心，重伤。', death:0.2, deathText:'燃尽最后一丝修为'}}, {label:'就此作别', eff:{}}]},
  /* ==== 紫（epic） ==== */
  {band:1, q:'legend', minAge:12, name:'灵药奇缘', once:true, syn:{cat:'zhi',catMult:1.2}, text:'你在一处秘境深处发现传说中的灵药——九叶紫芝！',
   opts:[{label:'当场服下', need:{attr:{气血:25}}, eff:{气血:15, 悟性:8, 力量:6, 神识:6}, evSet:'xiancao', shenPool:['菩提心经','冰封千里','土行遁'], evAdd:{flag:'mijing', eff:{气血:5}, txt:'你曾深入上古秘境，秘境根骨尽数炼化了九品紫芝的药力'}}, {label:'献给宗门', eff:{家境:15, 声望:12}}]},
  {band:1, q:'epic', minAge:20, name:'法宝碎片', syn:{cat:'wu',catMult:1.2}, text:'遗迹深处，一块残破的远古法宝静静悬浮，散发微光。', once:true, chainId:'hunbing', chainStart:true, step:'hb1', w:0.35,
   opts:[{label:'收入囊中', eff:{神识:4}, shenPool:['吞天噬地','九转金身','玄龟甲']}]},
  {band:1, q:'epic', minAge:24, name:'隐世高人', text:'你偶遇一位隐世的老修士，他似有收你为徒之意。', once:true, req:{lv:30},
   opts:[{label:'拜入师门', need:{attr:{悟性:30}}, eff:{悟性:10, 力量:8, 家境:5}, evSet:'master', shenPool:['乾坤挪移','天眼神通','太虚步']}, {label:'婉拒', eff:{}}]},
  {band:1, q:'legend', minAge:26, name:'天机老人', text:'山道旁，一位算命老者拦住你，直说你「命格不凡，有仙缘之相」。', once:true, w:0.35,
   opts:[{label:'求问天机', need:{attr:{气运:20}}, eff:{气运:8, 悟性:8}, evSet:'tianji', shenPool:['阴阳磨盘','天罗地网','日月同辉'], evAdd:{flag:'shenyi', eff:{气运:4}, txt:'你自幼便被天道一瞥，天机老人惊叹你仙缘在身，赠你一句天机'}}, {label:'只当诳语', eff:{}}]},
  {band:2, q:'legend', minAge:35, name:'上古秘境', syn:{wq:'ding',wqMult:1.2}, text:'传说中的上古秘境开启，其中机缘无数，也凶险万分。', once:true,
   opts:[{label:'孤身深入', need:{attr:{力量:40, 气血:30}}, evSet:'mijing', roll:{chance:0.4, extra:0.12, succ:{悟性:12, 力量:10, 灵动:8, 神识:8}, succText:'你夺得秘境至宝，脱胎换骨！', fail:{气血:-18}, failText:'秘境崩塌，九死一生。', death:0.2, deathText:'殒落于上古秘境'}}, {label:'结伴而行', roll:{chance:0.5, extra:0.05, succ:{悟性:8, 力量:6}, succText:'你分得一份机缘，小有收获。', fail:{气血:-8}, failText:'宝物被夺，狼狈而归。'}}]},
  {band:2, q:'epic', minAge:40, name:'太玄圣宗围剿', once:true, text:'太玄圣宗对你所在势力发难，刀兵相接。', ex:'wuhundian', req:{lv:55, notOrg:'太玄圣宗'}, // DL_RS_4.200：太玄圣宗成员不被己方围剿
   opts:[{label:'死战到底', need:{attr:{力量:35}}, roll:{chance:0.45, extra:0.05, succ:{声望:15,力量:10}, succText:'你杀出重围，名震一时。', fail:{气血:-16}, failText:'身负重伤，九死一生。', death:0.12, deathText:'战死于太玄圣宗围剿'}}, {label:'投诚保命', eff:{声望:-8, 家境:5}}]},
  /* ==== 金（legend） ==== */
  {band:1, q:'rare', minAge:18, name:'姻缘将至', text:'到了成家的年纪，身边也出现了一些缘分。是主动追求、接受家族安排，还是专注修炼？', once:true, type:'marriage', w:0.4,
   opts:[
     {label:'主动追求', need:{attr:{悟性:15}}, eff:{声望:3}, _marryMode:'pursue', _marryTxt:'你主动出击，追求心仪之人。'},
     {label:'接受家族安排', eff:{家境:3}, _marryMode:'arrange', _marryTxt:'你接受了家族的安排，门当户对。'},
     {label:'专注修炼', eff:{悟性:3}, _marryMode:'focus', _marryTxt:'你决定暂不考虑儿女情长，专注修炼。'}
   ]},
  {band:1, q:'legend', minAge:25, name:'神兽认主', syn:{cat:'shou',catMult:1.25}, text:'一头传说中的神兽幼崽主动亲近你，愿与你缔结契约。', once:true, req:{lv:40},
   opts:[{label:'缔结契约', need:{attr:{神识:40}}, eff:{力量:14, 灵动:10, 气血:8, 神识:10, 声望:20}, evSet:'shenshou'}, {label:'婉拒', eff:{}}]},
  {band:2, q:'legend', minAge:50, name:'仙器出世', syn:{cat:'wu',catMult:1.2}, text:'秘境深处，一件仙器法宝散发出惊天气息。', once:true, req:{lv:60},
   opts:[{label:'炼化法宝', need:{attr:{气血:40}}, bone:'仙器', roll:{chance:0.5, extra:0.1, succ:{力量:20, 气血:15, 灵动:10, 神识:10}, succText:'仙器炼化入体，道行惊天！', fail:{气血:-25}, failText:'法宝凶性难驯，你重伤垂死。', death:0.3, deathText:'被仙器反噬'}}, {label:'放弃', eff:{}}]},
  /* ==== 渡劫后期事件池（DL_RS_4.174：补后期内容短板，渡劫历练/仙途感应/渡劫争锋） ==== */
  /* 渡劫历练（90-94级） */
  {band:3, q:'epic', minAge:60, name:'渡劫游历', text:'你已臻渡劫之境，修仙界之上再难逢敌手。你决定游历修仙界，见识更广阔的天地。', once:true, req:{lv:[90,94]},
   opts:[{label:'深入极北之地', need:{attr:{气血:50}}, roll:{chance:0.5, extra:0.05, succ:{气血:10, 神识:8, 悟性:6}, succText:'极北苦寒磨砺了你的意志，你窥见了冰之大道的一角。', fail:{气血:-12}, failText:'极北之地太过凶险，你重伤而返。'}}, {label:'闯荡幽冥魔渊', need:{attr:{力量:50}}, roll:{chance:0.45, extra:0.05, succ:{力量:12, 气血:8, 声望:10}, succText:'幽冥魔渊的血战让你杀气凝实，道行大增！', fail:{气血:-15}, failText:'幽冥魔渊太过残酷，你险些殒命其中。', death:0.05, deathText:'殒命于幽冥魔渊'}}, {label:'隐居悟道', eff:{悟性:10, 神识:6}}]},
  {band:3, q:'epic', minAge:62, name:'渡劫争锋', text:'一位渡劫老怪向你发起挑战，声称要教训你这个后辈。', once:true, req:{lv:[90,94]},
   opts:[{label:'接受挑战', need:{attr:{力量:55}}, roll:{chance:0.45, extra:0.08, succ:{声望:20, 力量:8, 气运:5}, succText:'你击败了渡劫老怪，威名更盛！', fail:{气血:-18}, failText:'你败在了渡劫老怪手下，颜面尽失。'}}, {label:'婉拒', eff:{悟性:5}}]},
  {band:3, q:'rare', minAge:60, name:'收徒传艺', text:'一位天赋异禀的年轻人慕名而来，希望拜你为师。', req:{lv:[90,94]},
   opts:[{label:'收为弟子', need:{attr:{悟性:40}}, eff:{声望:10, 悟性:5, 灵石:200}, evSet:'has_disciple'}, {label:'婉拒', eff:{}}]},
  /* ==== 宗门任务（DL_RS_4.225：贡献获取渠道——巡山/炼丹/镇守） ==== */
  {band:2, q:'uncommon', minAge:20, name:'宗门任务·巡山值守', text:'宗门发布日常任务：巡山三日，防妖兽侵扰灵田。报酬为宗门贡献。', req:{hasOrg:true},
   opts:[{label:'接下任务', roll:{chance:0.75, extra:0.05, succ:{贡献:25, 灵石:150}, succText:'巡山无恙，宗门记你一功，贡献 +25。', fail:{气血:-3}, failText:'山中遇兽，你负了点轻伤，无功而返。'}}, {label:'专心修行', eff:{悟性:2}}]},
  {band:2, q:'uncommon', minAge:25, name:'宗门任务·炼丹侍奉', text:'丹房缺人，长老唤你去打下手，可顺带观摩丹道。', req:{hasOrg:true}, syn:{cat:'zhi',catMult:1.25},
   opts:[{label:'入丹房帮忙', need:{attr:{神识:20}}, roll:{chance:0.7, extra:0.05, succ:{贡献:30, 悟性:4}, succText:'丹成三炉，长老赞你眼力，贡献 +30。', fail:{悟性:-2}, failText:'你炸了一炉丹，悻悻而退。'}}, {label:'婉言推辞', eff:{}}]},
  {band:3, q:'epic', minAge:35, name:'宗门任务·镇守山门', text:'外敌来犯的消息传来，宗门征召强者镇守山门，重赏之下必有勇夫。', req:{hasOrg:true},
   opts:[{label:'应召镇守', need:{attr:{力量:30, 气血:28}}, roll:{chance:0.6, extra:0.08, succ:{贡献:50, 声望:10, 灵石:300}, succText:'强敌退去，你守山有功，贡献 +50。', fail:{气血:-10}, failText:'来敌凶悍，你负伤退下，宗门仍记你一功。', death:0.02, deathText:'殒命于山门守卫战'}}, {label:'闭关不出', eff:{悟性:3}}]},
  /* ==== 论道大会事件链（DL_RS_4.174：诸宗联办论道大会，中期目标感） ==== */
  {band:2, q:'epic', minAge:18, name:'论道大会·报名', text:'诸宗联办论道大会开幕！按修为分筑基/金丹/元婴三组（筑基期、金丹期、元婴期），同组论道，夺魁者冠绝同辈。', once:true, chainId:'dasai', chainStart:true, step:'ds1', req:{lv:[21,50]}, w:1.0,
   opts:[{label:'报名参赛', need:{attr:{力量:25}}, eff:{声望:5, 贡献:15}, evSet:'dasai_join'}, {label:'专注修炼', eff:{悟性:4}}]},
  {band:2, q:'epic', name:'论道·初赛', text:'初赛开打！同组论道，三轮循环，胜两场即可晋级复赛。', chainId:'dasai', step:'ds2', req:{ev:'dasai_join'},
   opts:[{label:'全力出战', need:{attr:{力量:20, 气血:18}}, roll:{chance:0.55, extra:0.05, succ:{声望:12, 力量:5, 灵石:200, 贡献:20}, succText:'三战两胜，你顺利晋级！', fail:{气血:-8, evClear:'dasai_join'}, failText:'强敌环伺，你未能出线，论道之旅就此结束。', death:0.03, deathText:'殒命于论道擂台'}}, {label:'稳扎稳打', need:{attr:{神识:18}}, roll:{chance:0.65, extra:0.03, succ:{声望:8, 悟性:4, 灵石:100}, succText:'你以巧取胜，稳步晋级。', fail:{气血:-4, evClear:'dasai_join'}, failText:'实力不济，遗憾出局，论道之旅就此结束。'}}]},
  {band:2, q:'legend', name:'论道·复赛', text:'复赛论道，五轮单败淘汰，每一场都不容有失。强者如云，你能走多远？', chainId:'dasai', step:'ds3', req:{ev:'dasai_join'},
   opts:[{label:'血战到底', need:{attr:{力量:28, 气血:25}}, roll:{chance:0.4, extra:0.08, succ:{声望:20, 力量:8, 灵石:500, 贡献:30}, succText:'你连克强敌，杀入决赛！', fail:{气血:-15, evClear:'dasai_join'}, failText:'你倒在了复赛的路上，虽败犹荣，论道之旅就此结束。', death:0.06, deathText:'殒命于论道死斗'}}, {label:'以智取胜', need:{attr:{神识:25, 悟性:25}}, roll:{chance:0.5, extra:0.05, succ:{声望:15, 悟性:6, 灵石:300}, succText:'你战术精妙，晋级决赛！', fail:{气血:-10, evClear:'dasai_join'}, failText:'对手实力碾压，你止步半决赛，论道之旅就此结束。'}}]},
  {band:2, q:'mythic', name:'论道·魁首之争', text:'决赛！诸宗目光汇聚于此。魁首将获得无上荣耀与丰厚奖励，名垂青史！', chainId:'dasai', step:'ds4', req:{ev:'dasai_join'},
   opts:[{label:'争夺冠军', need:{attr:{力量:35, 气血:32, 神识:28}}, roll:{chance:0.3, extra:0.1, succ:{声望:40, 力量:12, 气血:8, 神识:8, 灵石:1000, 气运:5, 贡献:50}, succText:'你力压群雄，夺得魁首！诸宗高呼你的名字！', fail:{气血:-20}, failText:'你与魁首失之交臂，获得亚军。', death:0.08, deathText:'殒命于魁首之争'}}, {label:'保季军', need:{attr:{力量:28}}, roll:{chance:0.6, extra:0.05, succ:{声望:20, 力量:5, 灵石:400}, succText:'你稳扎稳打，获得季军。', fail:{气血:-8}, failText:'你未能登上领奖台。'}}]},
    /* ==== 元始令（乾坤六令：集齐六枚入元始宗） ==== */
  {band:3, q:'rare', minAge:38, name:'幽冥魔渊·天令', ling:'天令', once:true, req:{lv:[60,999]}, w:0.8, text:'幽冥魔渊最深处，一间密室石门轰然洞开——石匣中静静躺着一枚青铜古令，上刻\"天\"字，隐有龙吟。',
   opts:[{label:'取走天令', eff:{声望:10}, txt:'天令入手——乾坤六令其一，元始宗传承之钥。'}]},
  {band:2, q:'rare', minAge:26, name:'妖兽遗冢·地令', ling:'地令', once:true, req:{lv:[25,999]}, w:0.8, text:'猎妖途中，你循着兽血踏入一座妖兽遗冢，冢心石台上供着一枚刻\"地\"字的玄铁令。',
   opts:[{label:'取走地令', eff:{声望:10}, txt:'地令入手——乾坤六令其二。'}]},
  {band:2, q:'rare', minAge:22, name:'古修洞府·黄令', ling:'黄令', once:true, req:{lv:[21,999]}, w:0.8, text:'云游之际，你误入一座古修洞府，禁制尽散后，一枚刻\"黄\"字的暖玉令现于蒲团之下。',
   opts:[{label:'取走黄令', eff:{声望:10}, shenPool:['星辰剑诀','虚空遁','御剑飞行'], txt:'黄令入手——乾坤六令其三。'}]},
  {band:2, q:'rare', minAge:26, name:'天机阁秘藏·宇令', ling:'宇令', once:true, req:{lv:[25,999]}, w:0.5, text:'天机阁百年一开的秘藏中，你于万千珍宝里摸到一枚刻\"宇\"字的星辰令，似有星辉流转。',
   opts:[{label:'取走宇令', eff:{声望:10}, txt:'宇令入手——乾坤六令其四。'}]},
  {band:3, q:'rare', minAge:60, name:'散仙遗蜕·宙令', ling:'宙令', once:true, req:{lv:[55,999]}, w:0.8, text:'一处散仙坐化之地，道韵未散，骸骨掌中握着一枚刻\"宙\"字的琉璃令，内蕴残存仙光。',
   opts:[{label:'取走宙令', eff:{声望:10}, txt:'宙令入手——乾坤六令其五。'}]},
  /* ==== 宗门内部论道（有宗门者可触发） ==== */
  {band:2, q:'uncommon', minAge:18, name:'宗门论道', req:{hasOrg:true}, w:0.35, text:'宗门内每月一期的论道会开讲，同门弟子切磋印证，胜者得宗门青睐。',
   opts:[{label:'登台论道', need:{attr:{神识:15}}, roll:{chance:0.55, extra:0.06, succ:{声望:8, 悟性:4, 灵石:80}, succText:'你技压同门，声名渐起。', fail:{气血:-4}, failText:'论道落败，闭关反思。'}}, {label:'旁听领悟', eff:{悟性:2, 神识:2}}]},
  /* ==== 事件链后续环节（仅由链驱动，强制出现） ==== */
  // DL_RS_4.201：元始宗六功法——链内 2 部（炼神秘录/元始诀）+ 独立池 4 部（乾坤步/元始破天指/原天三印/破妄法眼），集齐解锁隐藏势力元始宗
  /* XL_RS 4.38：势力功法专属化——元始宗六艺（元始诀/乾坤步/破妄法眼/元始破天指/原天三印/炼神秘录）仅元始宗藏经阁可习得，删除全部奇遇参悟事件 */
  /* ==== 元始宗传承（集齐六部功法后由 triggerEvent 钩子强制解锁，隐藏势力） ==== */
  {band:3, q:'legend', name:'元始宗传承', type:'tangmen', text:'六枚元始令齐聚于你——天、地、玄、黄、宇、宙，乾坤六令尽归己手，元始宗传承之门轰然洞开。是时候让元始宗之名重临修仙界了。', _special:true,
   opts:[{label:'执掌元始宗，开宗立派', _join:'元始宗', eff:{声望:30}}, {label:'隐于江湖，独行侠隐', eff:{悟性:10, 灵动:5}}]},
  {band:1, q:'rare', name:'妖兽领地', syn:{cat:'shou',catMult:1.25}, text:'妖域深处，你闯入了一处强大妖兽的领地，四周兽目森然。', chainId:'xingdou', step:'xingdou2',
   opts:[{label:'小心潜行', need:{attr:{灵动:25}}, roll:{chance:0.5, extra:0.1, succ:{灵动:10, 神识:8}, succText:'你摸清了领地脉络，全身而退。', fail:{气血:-12}, failText:'惊动兽群，险些葬身兽腹。', death:0.08, deathText:'葬身于万妖山脉'}}, {label:'原路返回', eff:{}}]},
  {band:2, q:'epic', name:'兽王传承', syn:{cat:'shou',catMult:1.25}, text:'森林之底，一头古老兽王残魂凝视着你，似要托付什么。', chainId:'xingdou', step:'xingdou3',
   opts:[{label:'接受兽王馈赠', need:{attr:{气血:30}}, eff:{力量:14, 气血:12, 神识:10, 声望:15}}, {label:'恭敬退走', eff:{悟性:8}}]},
  {band:1, q:'uncommon', name:'殿内考核', text:'太玄圣宗内每月例行考核，是你崭露头角的机会。', chainId:'wuhundian', chainStart:true, step:'whd1', needOrg:'太玄圣宗', w:0.35,
   opts:[{label:'全力以赴', need:{attr:{力量:20}}, roll:{chance:0.55, extra:0.05, succ:{声望:8, 力量:4}, succText:'你在考核中名列前茅，引来关注。', fail:{}, failText:'发挥平平，无人注意。'}}, {label:'深藏不露', eff:{悟性:3}}]},
  {band:1, q:'rare', name:'红衣长老赏识', text:'一位红衣长老注意到你，许你在太玄圣宗内更进一步。', chainId:'wuhundian', step:'whd2', needOrg:'太玄圣宗',
   opts:[{label:'承其赏识', need:{prestige:10}, eff:{家境:10, 声望:10, 悟性:5}}, {label:'婉拒', eff:{}}]},
  {band:2, q:'epic', name:'宗主青睐', text:'太玄圣宗宗主亲自召见，命你执掌一方重职。', chainId:'wuhundian', step:'whd3', needOrg:'太玄圣宗',
   opts:[{label:'领命就职', need:{prestige:30}, eff:{家境:15, 声望:20, 力量:8}}, {label:'推辞', eff:{悟性:6}}]},
  {band:1, q:'rare', name:'融合试炼', text:'远古法宝在你体内共鸣，一场融合试炼随之而来。', chainId:'hunbing', step:'hb2',
   opts:[{label:'凝神融合', need:{attr:{气血:30}}, roll:{chance:0.5, extra:0.1, succ:{力量:10, 气血:8, 神识:8}, succText:'法宝与你融为一体，气息大涨！', fail:{气血:-14}, failText:'法宝反噬，重伤难支。', death:0.1, deathText:'被法宝反噬而死'}}, {label:'封存法宝', eff:{}}]},
  {band:2, q:'rare', name:'法宝共鸣', syn:{cat:'wu',catMult:1.2}, text:'融合圆满的法宝，与你产生了更深层次的共鸣，远古之力灌入四肢百骸。', chainId:'hunbing', step:'hb3',
   opts:[{label:'引动共鸣', need:{attr:{神识:35}}, bone:'宝器', eff:{力量:8, 气血:6, 神识:6, 悟性:4}}, {label:'收敛气息', eff:{悟性:6}}]},
  /* ==== 势力专属事件链（DL_RS_4.83：龙象宗/风雷谷各一条，链终点给特色百分比奖励） ==== */
  {band:1, q:'rare', minAge:14, name:'龙象锤碑', text:'龙象宗，天下第一宗门。入门那天，你被引到镇宗之宝——万斤龙象锤碑前。', once:true, chainId:'hanyue', chainStart:true, step:'ht1', needOrg:'龙象宗', w:0.4,
   opts:[{label:'撼动锤碑', need:{attr:{力量:20}}, eff:{力量:5, 气血:3}}, {label:'量力而行', eff:{悟性:3}}]},
  {band:1, q:'rare', name:'锤法根基', text:'长老指点你龙象锤法根基，日挥万锤，枯燥而艰辛。', chainId:'hanyue', step:'ht2', needOrg:'龙象宗',
   opts:[{label:'苦练不辍', need:{attr:{力量:28}}, eff:{力量:6, 悟性:3}}, {label:'旁听悟道', eff:{悟性:4}}]},
  {band:2, q:'rare', minAge:22, name:'撼岳锤法', text:'长老传你龙象宗绝学「撼岳锤法」，九九八十一锤，连绵不绝。', chainId:'hanyue', step:'ht3', needOrg:'龙象宗',
   opts:[{label:'领悟锤意', need:{attr:{力量:40}}, roll:{chance:0.45, extra:0.1, succ:{力量:10, 悟性:6}, succText:'锤意初成，撼岳锤法已能连击三十六锤！', fail:{气血:-10}, failText:'锤法反噬，你气血翻涌、双臂酸麻。'}}, {label:'暂缓参悟', eff:{悟性:4}}]},
  {band:2, q:'epic', name:'撼岳大成', text:'九九八十一锤连环，力之所至，开山裂石。你真正掌握了撼岳锤法的精髓。', chainId:'hanyue', step:'ht4', needOrg:'龙象宗',
   opts:[{label:'锤意贯体', pctEff:{力量:0.15}, eff:{}}]},
  {band:1, q:'rare', minAge:14, name:'龙纹初显', text:'风雷谷，修仙界执掌风雷的御兽世家。觉醒时，你背上的龙纹隐隐发烫。', once:true, chainId:'landian', chainStart:true, step:'ld1', needOrg:'风雷谷', w:0.4,
   opts:[{label:'引动龙纹', need:{attr:{气血:18}}, eff:{气血:5, 力量:3}}, {label:'收敛气息', eff:{悟性:3}}]},
  {band:1, q:'rare', name:'龙血淬体', syn:{cat:'shou',catMult:1.25}, text:'家族秘库开启，一瓶稀世龙血赐下，助你淬炼肉身。', chainId:'landian', step:'ld2', needOrg:'风雷谷',
   opts:[{label:'浴龙血', need:{attr:{气血:25}}, roll:{chance:0.5, extra:0.05, succ:{气血:8, 力量:4}, succText:'龙血入体，肉身强横如铁！', fail:{气血:-10}, failText:'龙血暴烈，你痛得几欲昏厥。'}}, {label:'分次吸收', eff:{气血:4}}]},
  {band:2, q:'rare', minAge:24, name:'龙魂共鸣', syn:{cat:'shou',catMult:1.25}, text:'家族龙冢深处，一缕远古龙魂与你产生了共鸣。', chainId:'landian', step:'ld3', needOrg:'风雷谷',
   opts:[{label:'接纳龙魂', need:{attr:{神识:30}}, roll:{chance:0.45, extra:0.05, succ:{神识:8, 气血:6}, succText:'龙魂归位，你仿佛听见远古龙吟！', fail:{气血:-12}, failText:'龙魂凶戾，你神魂受创、元气大伤。'}}, {label:'退避三舍', eff:{悟性:3}}]},
  {band:2, q:'epic', name:'风雷龙威', syn:{cat:'shou',catMult:1.25}, text:'龙魂血脉彻底苏醒，风雷灵龙的威压自你体内迸发，群兽俯首、同辈战栗。', chainId:'landian', step:'ld4', needOrg:'风雷谷',
   opts:[{label:'龙威贯体', pctEff:{气血:0.15}, eff:{}}]},
  /* ==== 新增事件（扩充种类 + 平衡各年龄段触发概率） ==== */
  /* 白 · 幼年 */
  {band:0, q:'common', minAge:6, name:'修为初醒', text:'六岁这年，你第一次感到体内涌起一股温热的修为暖流。',
   opts:[{label:'请教长辈', need:{attr:{悟性:8}}, eff:{悟性:3}}, {label:'默默感受', eff:{气血:2, 神识:1}}]},
  {band:0, q:'common', minAge:9, name:'猎人父亲', text:'你的父亲是镇上最出名的猎人，这日他带你进山见识。',
   opts:[{label:'跟着学猎', need:{attr:{灵动:8}}, eff:{灵动:3, 力量:2}}, {label:'帮家里卖货', eff:{灵石:60}}]},
  /* 白 · 青年 */
  {band:1, q:'uncommon', minAge:21, name:'佣兵任务', text:'有佣兵团在招募修士，报酬丰厚，却也刀口舔血。',
   opts:[{label:'接危险任务', need:{attr:{力量:20}}, roll:{chance:0.5, succ:{力量:4, 灵动:3, 灵石:150}, succText:'任务完成，佣金落袋，道行也更扎实。', fail:{气血:-4}, failText:'任务凶险，你负伤而归。'}}, {label:'接护送任务', eff:{灵石:100, 声望:3}}]},
  /* 白 · 中年 / 老年 */
  {band:2, q:'uncommon', minAge:38, name:'宗门大比', text:'宗门年度大比开擂，全宗的目光都钉在擂台上——这是扬名立万、争夺资源的最佳机会。',
   opts:[{label:'报名参赛', need:{attr:{力量:26}}, roll:{chance:0.55, succ:{声望:8, 力量:4}, succText:'你一路取胜，宗门上下对你刮目相看。', fail:{气血:-4}, failText:'首轮告负，有些丢脸。'}}, {label:'旁观学习', eff:{悟性:3}}]},
  {band:3, q:'common', minAge:66, name:'回乡祭祖', text:'你告老还乡，回到出生的村庄。故乡早已物是人非。',
   opts:[{label:'重建故里', need:{money:300}, eff:{家境:-2, 声望:6}}, {label:'拜祭先祖', eff:{悟性:3, 气运:2}}]},
  /* 蓝 · 幼年 */
  {band:0, q:'rare', minAge:11, name:'寒潭淬体', syn:{cat:'zhi',catMult:1.25}, text:'村后有一方寒潭，传闻浸泡可淬炼体魄，却也凶险。',
   opts:[{label:'下潭淬体', need:{attr:{气血:20}}, roll:{chance:0.5, succ:{气血:6}, succText:'寒潭之力涌入四肢百骸，体魄大增！', fail:{气血:-6}, failText:'寒气入体，你大病一场。'}}, {label:'远远观望', eff:{悟性:2}}]},
  /* 蓝 · 青年 */
  {band:1, q:'uncommon', minAge:19, name:'修士殿试', text:'太玄圣宗三年一度的殿试开考，天才云集。', req:{lv:30},
   opts:[{label:'参加殿试', need:{attr:{力量:30}}, roll:{chance:0.5, extra:0.05, succ:{声望:10, 力量:4}, succText:'你在殿试中崭露头角，太玄圣宗注意到了你。', fail:{气血:-5}, failText:'殿试惨烈，你重伤落榜。'}}, {label:'不凑热闹', eff:{悟性:3}}]},
  {band:2, q:'rare', minAge:44, name:'通灵异兽', syn:{cat:'shou',catMult:1.25}, text:'一头修炼有成的六阶妖兽竟已颇具灵智，虽未至化形之境，却与你相识恨晚，颇谈得来。',
   opts:[{label:'与之结交', need:{attr:{神识:25}}, eff:{神识:8, 悟性:6}, evAdd:{flag:'shenshou', eff:{神识:4}, txt:'你与神兽缔结过契约，这头灵兽与你格外亲近'}}, {label:'婉言疏远', eff:{悟性:3}}]},
  {band:3, q:'common', minAge:64, name:'旧伤复发', text:'早年征战的暗伤复发，气血翻涌，你夜不能寐。',
   opts:[{label:'寻医求药', eff:{家境:-5, 气血:4}}, {label:'硬撑过去', need:{attr:{气血:30}}, eff:{气血:-6}}]},
  {band:3, q:'rare', minAge:74, name:'宿命一战', text:'一位同辈强者寻到你，要了结当年未竟的一战。', req:{ev:'chousha'},
   opts:[{label:'应战', need:{attr:{力量:35}}, evAdd:{flag:'jiudi', eff:{力量:4}, txt:'你曾斩落渡劫期宿敌，威名在前，气势已胜三分'}, roll:{chance:0.4, extra:0.1, succ:{声望:15, 力量:6}, succText:'你以老迈之躯胜出，传为佳话。', fail:{气血:-12}, failText:'力有不逮，你重伤败北。', death:0.12, deathText:'殒落于宿命一战'}}, {label:'避而不战', eff:{声望:-3}}]},
  /* 紫 · 青年 */
  {band:1, q:'epic', minAge:17, name:'灵根异象', text:'你的灵根觉醒之日，天现异象，八方强者侧目。', once:true,
   opts:[{label:'借势扬名', need:{attr:{气运:20}}, eff:{声望:15, 气运:5}}, {label:'低调潜修', eff:{悟性:8}}]},
  /* 紫 · 中年 / 老年 */
  {band:2, q:'epic', minAge:47, name:'宝器认主', syn:{cat:'wu',catMult:1.2}, text:'拍卖会上，一件宝器法宝竟主动与你产生共鸣。', once:true,
   opts:[{label:'倾尽家财拍下', need:{money:1500}, bone:'宝器', eff:{灵石:-1500, 力量:12, 气血:8}}, {label:'忍痛放弃', eff:{悟性:4}}]},
  {band:3, q:'epic', minAge:72, name:'武道巅峰', text:'你将毕生所学融会贯通，欲创出独属于自己的绝学。', once:true,
   opts:[{label:'闭关创法', need:{attr:{力量:60}}, evAdd:{flag:'master', eff:{力量:6}, txt:'你融入了师门绝学，毕生所学更上层楼'}, roll:{chance:0.5, extra:0.05, succ:{力量:14, 悟性:8}, succText:'绝学大成，你跻身当世武学宗师之列！', fail:{气血:-8}, failText:'气血已衰，闭关无果。'}}, {label:'广传门人', eff:{声望:12, 悟性:6}}]},
  /* 金 */
  {band:0, q:'legend', minAge:6, name:'天道一瞥', text:'恍惚之间，仿佛一道天道意志在你身上停留了一瞬，冥冥中气运流转。', once:true,
   opts:[{label:'铭记于心', need:{attr:{气运:25}}, eff:{气运:8, 神识:6}, evSet:'shenyi'}, {label:'当作幻觉', eff:{悟性:4}}]},
  /* ==== 新增事件（DL_RS_4.7 扩充修仙界情节，平衡各品质/年龄段触发概率） ==== */
  /* 白 · 幼年 / 青年 */
  {band:0, q:'uncommon', minAge:7, name:'初涉妖林', syn:{cat:'shou',catMult:1.25}, text:'长辈带你去猎妖森林外围见识世面，一路指点你辨认妖兽的习性。',
   opts:[{label:'认真聆听', need:{attr:{悟性:10}}, eff:{悟性:3}}, {label:'跃跃欲试', eff:{灵动:2}}]},
  {band:1, q:'uncommon', minAge:16, name:'宗门考核', text:'附近有大宗门设点招生，传闻能通过考核者皆非凡人。', req:{notOrg:true},
   opts:[{label:'前去挑战', need:{attr:{力量:20}}, roll:{chance:0.5, extra:0.05, succ:{力量:6, 声望:8}, succText:'你竟通过了怪物的考核！', fail:{气血:-4}, failText:'被拒之门外，悻悻而归。'}}, {label:'敬而远之', eff:{悟性:2}}]},
  {band:1, q:'common', minAge:27, name:'大周夜市', text:'大周城夜市灯火如昼，叫卖声、喧闹声混着烤肉的焦香扑面而来，你与友人漫步其间，一时忘了江湖恩怨。',
   opts:[{label:'尽情游玩', need:{money:100},
 eff:{家境:3, 悟性:1}}, {label:'驻足听书', eff:{悟性:3}}]},
      {band:1, q:'common', minAge:16, name:'夜读残卷', text:'一册残破的杂记被你翻了又翻，字里行间似有乾坤。', opts:[{label:'挑灯细读',eff:{悟性:3}},{label:'困倦睡下',eff:{神识:1}}]},
/* 白 · 中年 / 老年 */
  {band:2, q:'common', minAge:31, name:'故友重逢', text:'茶楼里，儿时的伙伴已是满脸风霜，拉着你絮叨这些年的柴米油盐。他的灵根终其一生未能突破，如今只盼孩子能争口气。',
   opts:[{label:'把酒言欢', eff:{悟性:3, 家境:2}}, {label:'寒暄而过', eff:{悟性:1}}]},
  {band:2, q:'uncommon', minAge:38, name:'商队护卫', text:'商队主事亲自登门，开出优厚佣金聘你护卫——只是那路线要穿过落日森林边缘，传闻最近不太平。',
   opts:[{label:'应下护卫', need:{attr:{力量:24}}, roll:{chance:0.5, extra:0.05, succ:{灵石:200, 力量:3}, succText:'一路平安，佣金落袋。', fail:{气血:-5}, failText:'途中遇袭，你挂了彩。'}}, {label:'婉拒', eff:{悟性:2}}]},
  {band:3, q:'common', minAge:60, name:'著书立说', text:'你将一生所学整理成书，欲留之后人。',
   opts:[{label:'著书传世', need:{attr:{悟性:40}}, eff:{悟性:8, 声望:8}}, {label:'封存箱底', eff:{悟性:3}}]},
  /* 蓝 · 幼年 / 青年 */
  {band:0, q:'rare', minAge:12, name:'秘境小试', syn:{wq:'ding',wqMult:1.2}, text:'附近出现一处小型秘境，长辈带你入内试炼，传说其中藏有前人之物。',
   opts:[{label:'深入寻宝', need:{attr:{力量:20}}, roll:{chance:0.45, extra:0.05, succ:{力量:8, 灵动:6, 悟性:4}, succText:'你寻得前人遗物，收获颇丰！', fail:{气血:-6}, failText:'触动了禁制，狼狈退出。'}}, {label:'外围观摩', eff:{悟性:3}}]},
  /* DL_RS_4.207：幽冥魔渊完整事件链——寻入口（炼虚期+低概率终生一次）→魔渊杀戮场百连胜（强制四轮）→深渊路 */
  {band:3, q:'legend', minAge:60, name:'幽冥魔渊·入口', _manual:true, _special:true, once:true, req:{lv:60}, text:'血色迷雾于修仙界某处翻涌，一座古老城池的轮廓在雾中若隐若现——传闻那便是幽冥魔渊，修仙界最血腥之地，九死一生，亦藏极致机缘。你已臻至化神之境，毅然踏入。',
   opts:[{label:'踏入入口', _shaEnter:true, eff:{声望:10}}, {label:'谨慎离开，待日后功成再来', eff:{气运:1}, txt:'幽冥魔渊凶名在外，你按下好奇心转身离去——江湖路远，来日方长。'}], _shaOpen:true},
  {band:3, q:'legend', name:'魔渊杀戮场', _manual:true, _special:true, text:'魔渊杀戮场——百人同场厮杀，唯胜者生。你已连战数轮，此轮再胜，距百连胜更近一步；败则重创退出，再无重来。',
   opts:[{label:'提刀入场', _shaArena:true}]},
  {band:1, q:'uncommon', minAge:21, name:'法宝黑市', syn:{cat:'wu',catMult:1.25}, text:'黑市中出现一件灵器法宝，要价不菲，真假难辨。',
   opts:[{label:'倾囊买下', need:{money:900}, bone:'灵器', eff:{灵石:-900, 气血:8}}, {label:'放弃', eff:{悟性:2}}]},
  /* 蓝 · 中年 / 老年 */
  {band:2, q:'rare', minAge:44, name:'宗门内斗', text:'你所在势力爆发内斗，各派系明争暗斗，波及到你。', req:{hasOrg:true},
   opts:[{label:'力挽狂澜', need:{attr:{力量:40}}, roll:{chance:0.45, extra:0.05, succ:{声望:12, 力量:6}, succText:'你平息内乱，威望大涨。', fail:{气血:-10, 声望:-4}, failText:'卷入漩涡，身心俱疲。', death:0.08, deathText:'死于内斗漩涡'}}, {label:'明哲保身', eff:{悟性:4}}]},
  {band:3, q:'common', minAge:63, name:'弟子闯祸', text:'你的弟子在外闯下大祸，对方登门问罪。', req:{hasChild:true},
   opts:[{label:'出面摆平', need:{money:300}, eff:{灵石:-300, 悟性:4}}, {label:'严加管教', eff:{悟性:5}}]},
  /* 紫 */
  {band:1, q:'epic', minAge:24, name:'阴阳地脉', syn:{cat:'zhi',catMult:1.2}, text:'你在一处极寒极热之地，发现一条阴阳地脉，传说其孕育灵植仙草。', once:true,
   opts:[{label:'采摘仙草', need:{attr:{气血:30}}, eff:{气血:14, 悟性:8, 神识:6}}, {label:'谨记方位', eff:{悟性:10}}]},
  {band:2, q:'legend', minAge:46, name:'妖兽故交', syn:{cat:'shou',catMult:1.25}, text:'一头高阶妖兽竟与你相谈甚欢，视你为知己。', once:true, req:{lv:55},
   opts:[{label:'缔结盟约', need:{attr:{神识:40}}, eff:{力量:12, 气血:10, 声望:18}}, {label:'谨慎保持距离', eff:{悟性:6}}]},
  {band:2, q:'epic', minAge:50, name:'上古丹方', syn:{cat:'zhi',catMult:1.25}, text:'你得一张上古丹方，传言可洗筋伐髓，脱胎换骨。', once:true, req:{ev:'xiancao'},
   opts:[{label:'寻药炼制', need:{money:600}, eff:{灵石:-600, 气血:12, 悟性:6}, evAdd:{flag:'mijing', eff:{悟性:4}, txt:'秘境采得的珍稀药引，让丹方功效更上一层'}}, {label:'转售他人', eff:{灵石:500}}]},
  {band:3, q:'epic', minAge:68, name:'武道真意', once:true, text:'你于垂暮之年重读半生战录，忽然窥见一丝武道真意。',
   opts:[{label:'融会贯通', need:{attr:{悟性:55}}, eff:{力量:12, 悟性:8}}, {label:'含笑放下', eff:{悟性:6}}]},
  /* 金 */
  {band:3, q:'legend', minAge:75, name:'天启', text:'弥留之际，天光破晓，你仿佛看见了自己的一生。', once:true, req:{lifeLeft:8},
   opts:[{label:'顿悟', need:{attr:{悟性:60}}, eff:{悟性:10, 气运:6}}, {label:'安然', eff:{气血:5}}]},
  /* 大机缘事件已移除（变异机制废除） */
  /* ==== 新增事件（DL_RS_4.12 扩充白事件种类，缓解白事件频繁刷脸；每事件至少一个选项带属性要求） ==== */
  {band:0, q:'common', minAge:8, name:'看家护院', text:'镇上的富户招童工看家护院，报酬虽薄，也能贴补家用。',
   opts:[{label:'踏实值守', need:{attr:{气血:8}}, eff:{灵石:50, 气血:2}}, {label:'偷懒摸鱼', eff:{灵石:20}}]},
  {band:0, q:'common', minAge:9, name:'母亲病重', text:'母亲染上风寒，卧床不起，家中愁云惨淡。',
   opts:[{label:'进山采药', need:{attr:{灵动:10}}, roll:{chance:0.6, succ:{气血:4}, succText:'你采得灵药，母亲转危为安。', fail:{气血:-3}, failText:'山路凶险，你跌了一跤，药也没采到。'}}, {label:'四处求医', eff:{灵石:-50, 家境:2}}]},
  {band:1, q:'uncommon', minAge:20, name:'宗门任务', text:'宗门长老将一枚令牌拍在你掌心，任务卷宗上朱批「急」字——报酬颇丰，责任也不轻。', req:{hasOrg:true},
   opts:[{label:'接下重担', need:{attr:{力量:22}}, eff:{灵石:150, 声望:5}}, {label:'婉言推脱', eff:{悟性:2}}]},
  {band:1, q:'uncommon', minAge:23, name:'妖兽药材', syn:{cat:'zhi',catMult:1.25}, text:'猎妖森林外围，有商贩高价收购年份足的药草。',
   opts:[{label:'进林采集', need:{attr:{灵动:20}}, roll:{chance:0.55, succ:{灵石:300, 灵动:3}, succText:'你采到几株值钱的药草，卖了好价钱。', fail:{气血:-5}, failText:'林中遇兽，你空手而回。'}}, {label:'不为所动', eff:{悟性:2}}]},
  {band:2, q:'uncommon', minAge:40, name:'论道大会', text:'修仙界论道大会在大周城召开，强者云集，以论道为名，实为切磋扬名——登台者，一战可定江湖地位。',
   opts:[{label:'登台论道', need:{attr:{悟性:32}},
 eff:{悟性:6, 声望:8}}, {label:'台下观摩', eff:{悟性:3}}]},
{band:2, q:'uncommon', minAge:48, name:'法宝商队', syn:{cat:'wu',catMult:1.25}, text:'一支护送稀有法宝的商队途经此地，重金招揽强者随行。',
   opts:[{label:'应征随行', need:{attr:{力量:30}}, roll:{chance:0.5, extra:0.05, succ:{灵石:400, 力量:3}, succText:'一路平安，你挣得厚厚一袋灵石。', fail:{气血:-6}, failText:'途中遇袭，你挂了彩。'}}, {label:'婉拒', eff:{悟性:2}}]},
  {band:3, q:'common', minAge:58, name:'云游四方', text:'浮生半世，你站在窗前看尽人间烟火，忽然生出放下一切、去修仙界最深处走一遭的念头。',
   opts:[{label:'说走就走', need:{money:200}, eff:{悟性:6, 气血:4}}, {label:'仍旧守在家中', eff:{悟性:2}}]},
  {band:3, q:'uncommon', minAge:62, name:'传功长老', text:'你所在的势力登门相请，欲聘你出任传功长老，为后辈传道授业。', req:{hasOrg:true, minQuality:'you', lv:60},
   opts:[{label:'应下重职', need:{attr:{悟性:35}},
 eff:{声望:10, 悟性:5}, evAdd:{flag:'master', eff:{声望:8}, txt:'名师出高徒，你的师承成了宗门最响的招牌'}}, {label:'谢绝挂职', eff:{悟性:3}}]},
/* ==== 逆天机缘（DL_RS_4.64）：触发概率极低（w≈0.05），触发后获得限时「气运眷顾」修炼 buff
       或修为/属性暴涨——主角级命格专属，可冲击更高境界 ==== */
  {band:1, q:'legend', minAge:12, name:'圣药·九转金莲', syn:{cat:'zhi',catMult:1.2}, text:'万载难逢的九转金莲在你眼前绽放，莲香沁人心脾——传说服之可脱胎换骨、直抵天骄之境！', once:true, w:0.05,
   opts:[{label:'服下金莲', eff:{气血:15, 悟性:12, 神识:12}, fortune:{years:6, mult:5}, heroTxt:'九转金莲入腹，仙药之力在四肢百骸炸开，你仿佛听见了命运之门洞开的声音！'}, {label:'炼制成丹转售', eff:{灵石:2000}}]},
  {band:2, q:'legend', minAge:30, name:'幽冥魔渊·深渊路', _manual:true, _special:true, syn:{wq:'ding',wqMult:1.2}, text:'你在幽冥魔渊杀穿百场，直达深渊路入口——传说通过者将磨砺出无双杀意。', once:true, req:{lv:40, shaKills:100},
   opts:[{label:'闯深渊路', need:{attr:{力量:60}}, roll:{chance:0.5, extra:0.1, succ:{力量:20, 灵动:16, 神识:18, 气运:10}, succText:'你杀穿深渊路，杀意凝而不散！', fail:{气血:-25}, failText:'深渊路凶险，你重伤败退。', death:0.25, deathText:'陨落于深渊路'}, fortune:{years:4, mult:4}, heroTxt:'深渊路尽头，杀意灌体——你已走上主角的通天路。'}, {label:'止步于此', eff:{悟性:5}}]},
  /* ==== 修士对决（DL_RS_4.99）==== */
  {band:1, q:'rare', minAge:16, maxAge:70, name:'修士挑战赛', text:'镇上的武斗场今日开擂，三教九流的修士摩拳擦掌，彩金丰厚。', type:'duel', mode:'arena',
   opts:[{label:'下场迎战', need:{attr:{力量:20}}, eff:{}, evSet:'duelist', duelTxt:'实战对决·胜败依道行而定'}, {label:'观战下注', roll:{chance:0.5, succ:{灵石:300}, succText:'你押对了人，小赚一笔。', fail:{灵石:-150}, failText:'看走了眼，血本无归。'}, duelTxt:'押注对决·胜负各半'}, {label:'不凑热闹', eff:{}, duelTxt:'作壁上观'}]},
  {band:1, q:'rare', minAge:15, maxAge:38, name:'太玄圣宗学院赛', text:'太玄圣宗主办的区域学院赛开赛——这是年轻修士崭露头角的舞台，胜者可获太玄圣宗推荐，直通更高规格的赛事。', once:true, type:'duel', mode:'elite', req:{lv:15}, w:0.5,
   opts:[{label:'以学院之名报名', eff:{}, evAdd:{flag:'duelist', eff:{声望:15}, txt:'身经百战的老将一登场，令对手未战先怯'}, duelTxt:'预选赛·晋级赛·总决赛层层闯关'}, {label:'闭关修炼，错过盛会', eff:{悟性:2}, duelTxt:'放弃参赛·安心修炼'}]},
  {band:2, q:'epic', minAge:30, maxAge:70, name:'生死斗', text:'地下的黑角斗场里，生死状一签，胜者通吃，败者非死即残。', type:'duel', mode:'death', req:{lv:35},
   opts:[{label:'押上性命应战', need:{attr:{气血:35}}, eff:{}, duelTxt:'生死对决·胜者通吃，败者非死即残'}, {label:'只是观战', eff:{}, duelTxt:'作壁上观'}]},
  /* ==== 事件链·阴阳灵泉（DL_RS_4.101 多分支链）==== */
  {band:2, q:'epic', minAge:25, maxAge:60, name:'阴阳灵泉', syn:{cat:'zhi',catMult:1.2}, text:'一处绝谷之中，你发现一汪奇潭——一半冰封千里，一半烈焰翻腾，正是传说中能淬体炼魂的阴阳灵泉。', once:true, chainId:'binghuo', chainStart:true, step:'bh1', w:0.3, req:{lv:35},
   opts:[{label:'下潭一试', eff:{}}]},
  {band:2, q:'epic', name:'冰火淬体', syn:{cat:'zhi',catMult:1.2}, text:'潭水冰寒刺骨、火泉灼热欲焚，你只能择一而浴，贪多必伤根基。', chainId:'binghuo', step:'bh2',
   opts:[{label:'冰泉淬体', need:{attr:{气血:40}}, eff:{}, chainGoto:'bh3'}, {label:'火泉炼魂', need:{attr:{神识:40}}, eff:{}, chainGoto:'bh4'}, {label:'暂不淬体，离开此地', eff:{}, chainEnd:true}]},
  {band:2, q:'epic', name:'玄冰炼体', syn:{cat:'zhi',catMult:1.2}, text:'冰泉之力渗入骨髓，你的肉身在极寒中蜕变，百炼成钢，坚逾精铁。', chainId:'binghuo', step:'bh3', chainEnd:true,
   opts:[{label:'承此造化', eff:{气血:10, 力量:6}}]},
  {band:2, q:'epic', name:'离火炼魂', syn:{cat:'zhi',catMult:1.2}, text:'离火焚尽杂念，你的神识在烈焰中淬炼得纯净无瑕，感知入微。', chainId:'binghuo', step:'bh4', chainEnd:true,
   opts:[{label:'承此造化', eff:{神识:10, 悟性:5}}]},
  /* ==== 事件链·大楚权谋（DL_RS_4.101 多分支链）==== */
  {band:2, q:'epic', minAge:35, maxAge:65, name:'大楚宫廷', text:'你名声在外，被大楚皇朝招入宫廷。庙堂之上暗流涌动，太子与四皇子争储正烈，站队成了唯一的生存之道。', once:true, chainId:'xingluo', chainStart:true, step:'xl1', w:0.26, req:{lv:45, prestige:80},
   opts:[{label:'谨言慎行，静观其变', eff:{}}]},
  {band:2, q:'epic', name:'夺嫡站队', text:'两方都向你递来橄榄枝。这一步踏错，便是万劫不复；踏对了，便是从龙之功。', chainId:'xingluo', step:'xl2',
   opts:[{label:'支持太子，求个正统', need:{prestige:100}, eff:{}, chainGoto:'xl3'}, {label:'投靠四皇子，搏一场富贵', eff:{}, chainGoto:'xl4'}]},
  {band:2, q:'epic', name:'从龙之功', text:'太子登基，你因从龙之功受封侯爵，赐金赏地，大楚皇朝的国运与你绑在了一起。', chainId:'xingluo', step:'xl3', chainEnd:true,
   opts:[{label:'谢主隆恩', eff:{声望:30, 灵石:2000}}]},
  {band:2, q:'rare', name:'夺嫡风波', text:'四皇子势弱，谋事不密，事败被幽。你因暗中相助而遭牵连，仓皇逃出大楚。', chainId:'xingluo', step:'xl4', chainEnd:true,
   opts:[{label:'远走避祸', eff:{声望:-10, 悟性:5}, roll:{chance:0.4, succ:{灵石:1500}, succText:'逃亡途中你卷走了四皇子埋下的窖藏，也算不虚此行。', fail:{灵石:-300}, failText:'追兵截了你的去路，损失惨重才得以脱身。'}}]},


  /* ==== DL_RS_4.120：赌机缘事件（高风险高回报，增强抉择张力）==== */
  {band:1, q:'uncommon', minAge:18, maxAge:45, name:'地下武斗', text:'城镇地下的黑市武斗场，庄家开出了你从未见过的赔率——只要敢上，就能一夜暴富。', req:{lv:15},
   opts:[{label:'下场搏命', need:{attr:{力量:22}}, roll:{chance:0.4, extra:0.10, succ:{灵石:800,力量:4,声望:8}, succText:'你连战三场，拳拳到肉，赌徒们为你的名字疯狂呐喊。', fail:{气血:-10}, failText:'对手是修炼多年的老手，你被揍得吐血败退。', death:0.05, deathText:'战死于地下武斗场'}}, {label:'押注旁观', roll:{chance:0.5, succ:{灵石:300}, succText:'你押对了，赚了一笔横财。', fail:{灵石:-200}, failText:'押错了人，赔了个底朝天。'}}, {label:'不凑热闹', eff:{}}]},
  {band:1, q:'rare', minAge:20, maxAge:60, name:'古墓探险', text:'你在一处荒山中偶遇一座被青藤掩盖的古墓，墓门半开，阴气森森，隐约可见内里宝光流转。',
   opts:[{label:'入墓探宝', need:{attr:{悟性:30}}, roll:{chance:0.4, extra:0.08, succ:{悟性:8,灵石:500,力量:4}, succText:'你破开重重机关，得见墓主遗藏——一卷神通手札与半袋灵石。', fail:{气血:-12}, failText:'墓中机关连环触发，你九死一生逃出，浑身是伤。', death:0.08, deathText:'葬身古墓'}}, {label:'封墓退走', eff:{悟性:2}}]},
  {band:1, q:'rare', minAge:22, maxAge:50, name:'拦路豪强', text:'归途遇一伙亡命修士打劫，为首者竟是大名鼎鼎的独行盗。',
   opts:[{label:'硬拼到底', need:{attr:{力量:35}}, roll:{chance:0.4, extra:0.08, succ:{灵石:600,力量:5,声望:8}, succText:'你杀退群盗，缴获颇丰，独行盗的头颅成了你威名的注脚。', fail:{气血:-12}, failText:'寡不敌众，你身中数刀逃出生天。', death:0.08, deathText:'死于乱刀之下'}}, {label:'破财消灾', need:{money:200}, eff:{灵石:-200,气血:-2}}, {label:'机敏遁走', need:{attr:{灵动:25}}, eff:{灵动:2}}, {label:'忍气吞声', eff:{声望:-4,气血:-2}}]},
  {band:2, q:'rare', minAge:30, maxAge:70, name:'豪赌一夜', text:'城中最大的赌坊今夜豪客云集，据说有人一夜之间赢下半个身家。', req:{money:300},
   opts:[{label:'押上重注', need:{money:800}, roll:{chance:0.35, extra:0.05, succ:{灵石:2000}, succText:'你手气冲天，一夜暴富，赌坊主的脸都绿了。', fail:{灵石:-1000}, failText:'倾家荡产，你把大半积蓄输了个精光。'}}, {label:'小赌怡情', roll:{chance:0.5, succ:{灵石:300}, succText:'小赢一笔，见好就收。', fail:{灵石:-150}, failText:'小输一注，无伤大雅。'}}, {label:'转身离开', eff:{}}]},
  {band:2, q:'rare', minAge:32, maxAge:75, name:'吞服秘丹', text:'一位邋遢老者递给你一枚腥红丹药，言称「服之脱胎换骨，反噬则万劫不复」。',
   opts:[{label:'冒险吞服', need:{attr:{气血:30}}, roll:{chance:0.35, extra:0.05, succ:{气血:10,悟性:6,力量:6}, succText:'药力如熔岩冲刷四肢百骸，你的根基被重新淬炼，竟是真的神丹！', fail:{气血:-15,力量:-8}, failText:'药性暴烈如刀，你经脉受创，数月动弹不得。', death:0.10, deathText:'为丹药所噬，七窍流血而亡'}}, {label:'婉拒离开', eff:{}}]},
  {band:2, q:'epic', minAge:40, maxAge:80, name:'秘境夺宝', once:true, text:'传闻中的上古秘境入口今日现世，各国强者闻风而动，秘境深处有一桩天大的机缘在等着主人。', req:{lv:60}, syn:{wq:'ding',wqMult:1.2},
   opts:[{label:'深入争夺', need:{attr:{力量:45}}, roll:{chance:0.3, extra:0.08, succ:{力量:8,灵动:6,灵石:1200,声望:15}, succText:'你力压群雄，夺得秘境至宝，一战成名。', fail:{气血:-20}, failText:'秘境凶险远超想象，你重伤而逃，几乎殒命。', death:0.15, deathText:'陨落于秘境争夺'}}, {label:'外围捡漏', roll:{chance:0.5, succ:{灵石:400,悟性:3}, succText:'你在外围捡到些边角料，也算不虚此行。', fail:{气血:-4}, failText:'被秘境余波震伤。'}}, {label:'不趟浑水', eff:{}}]},
  /* ==== XL_RS 4.50：功德业力事件——正邪抉择，功德/业力仅影响渡劫 ==== */
  {band:0, q:'common', minAge:6, name:'寒夜乞儿', text:'村口雪地里蜷着个冻僵的小乞儿——你若不管，他怕是熬不过今夜。',
   opts:[{label:'施舍饭食', eff:{功德:2, 灵石:-10}, txt:'你把热饭和几枚灵石塞进他手里，他眼里的光亮了又亮。'}, {label:'漠然离去', eff:{业力:1}, txt:'你转身走开，雪地里那团小小的黑影渐渐模糊。'}]},
  {band:0, q:'common', minAge:8, name:'恶少欺老', text:'镇口药摊前，恶少正掀翻老人的药篓，围观众人敢怒不敢言。',
   opts:[{label:'挺身喝止', need:{attr:{灵动:10}}, roll:{chance:0.6, succ:{功德:3, 声望:3}, succText:'你一声断喝，恶少悻悻而去，众人纷纷叫好。', fail:{气血:-2}, failText:'恶少反手推搡，你踉跄后退，药篓散了一地。'}}, {label:'低头走开', eff:{业力:1}, txt:'多一事不如少一事，你终究没有上前。'}]},
  {band:0, q:'uncommon', minAge:12, name:'失金不昧', text:'坊市地上躺着一只鼓鼓的灵石袋，四下无人注意。',
   opts:[{label:'交给坊市执事', eff:{功德:3, 声望:2}, txt:'执事记下你的名姓，夸你少年心性纯良。'}, {label:'顺手揣走', eff:{业力:2, 灵石:50}, txt:'你不动声色地拾起，快步没入人群。'}]},
  {band:1, q:'uncommon', minAge:16, name:'猎妖真相', text:'村中悬赏除妖，你费尽心力斩妖归来，却发现这妖原是被人豢养的灵宠。',
   opts:[{label:'如实相告，拒领赏钱', eff:{功德:4, 声望:4}, txt:'你道出实情，村人半信半疑，却敬你行事磊落。'}, {label:'瞒下真相领赏', eff:{业力:3, 灵石:80}, txt:'你收下赏钱，把那点疑窦压进心底。'}]},
  {band:1, q:'rare', minAge:20, name:'邪修掳人', text:'荒野之上，一名邪修正以缚魂术掳掠凡人，欲炼魂祭器，哀嚎声声。',
   opts:[{label:'出手相救', need:{attr:{力量:18}}, roll:{chance:0.45, succ:{功德:8, 声望:8, 力量:4}, succText:'你剑出如风，邪修负伤遁走，被掳者叩首谢恩。', fail:{气血:-10}, failText:'邪修凶悍，你拼死护住几人，自己却血溅当场。', death:0.08, deathText:'力战邪修而亡'}}, {label:'绕道避开', eff:{业力:6, 悟性:2}, txt:'你敛息绕行，耳边的哀嚎渐远，心底却像压了块石头。'}]},
  {band:1, q:'rare', minAge:24, name:'灵药之争', text:'秘境之中，你与一位同道同时发现一株千年灵芝，四目相对，气氛渐凝。',
   opts:[{label:'公平斗法定归属', eff:{功德:3}, roll:{chance:0.5, succ:{气血:8, 声望:3}, succText:'你技高一筹，灵芝归你，对方拱手认输。', fail:{悟性:3}, failText:'对方略胜半筹，却愿与你平分药力。'}}, {label:'趁其不备夺药', eff:{业力:5, 气血:10}, txt:'你骤然出手卷走灵芝，身后传来怒骂，你头也不回。'}]},
  {band:2, q:'epic', minAge:32, name:'超度怨魂', text:'古战场怨魂千年不散，夜夜厉啸，方圆百里生灵不安。',
   opts:[{label:'以神识超度，送其往生', need:{attr:{神识:30}}, eff:{功德:12, 神识:6, 气运:3}, txt:'你诵念安魂真言七日，怨气化云消散，百里重归安宁。'}, {label:'引魂炼煞，收为己用', eff:{业力:10, 神识:8, 力量:4}, txt:'你布下炼魂阵，千魂入炉，一股凶煞之力灌入经脉。'}]},
  {band:2, q:'epic', minAge:38, name:'魔修屠村', text:'你路过一村，魔道修士正以全村性命炼血煞，哀嚎震天，血气弥漫。',
   opts:[{label:'挺身血战', need:{attr:{气血:32}}, roll:{chance:0.4, succ:{功德:15, 力量:8, 声望:12}, succText:'你浴血搏杀，魔修陨落当场，残存村民跪了一地。', fail:{气血:-15}, failText:'你重伤垂死，只救下寥寥数人，魔修遁走。', death:0.1, deathText:'力战魔修而亡'}}, {label:'避祸远遁', eff:{业力:8, 灵动:3}, txt:'你封住口鼻远遁而去，身后的血气像永远挥之不去的梦魇。'}]},
  {band:2, q:'legend', minAge:50, name:'天道酬善', text:'你一生行善积德，冥冥中天道似有感应，一缕玄机悄然落于眉间。',
   opts:[{label:'静悟玄机', eff:{功德:10, 气运:5, 神识:8}, txt:'你盘膝三日，感悟天道酬善之理，识海澄澈如镜。'}, {label:'广施善缘', eff:{功德:10, 声望:12, 灵石:-100}, txt:'你散尽百金济困扶危，善名远播。'}]},
  {band:3, q:'legend', minAge:62, name:'业火焚心', text:'多年杀业缠身，心魔在识海中蠢蠢欲动，业火自心底无声燃起。',
   opts:[{label:'静心忏悔', eff:{业力:-8, 气血:-5}, txt:'你闭关三月诵经赎罪，业火渐熄，道心重归澄明。'}, {label:'以杀止杀', roll:{chance:0.5, succ:{业力:8, 力量:6}, succText:'你杀入魔窟以杀证道，心魔暂退，煞气更盛。', fail:{业力:5, 气血:-8}, failText:'业火反噬，你险些走火入魔。', death:0.12, deathText:'业火焚心，身死道消'}}]},
  {band:3, q:'mythic', minAge:68, name:'功德金身', text:'功德圆满，天道降下金辉，你的道体隐隐凝出一层功德金身。',
   opts:[{label:'受此金身', eff:{功德:15, 气血:10, 神识:8, 气运:5}, txt:'金辉入体，你的道体坚不可摧，隐隐有仙光流转。'}, {label:'婉拒而内敛', eff:{功德:12, 悟性:8, 气运:3}, txt:'你散去金辉反哺道基，根基愈发浑厚。'}]},
  // —— XL_RS 4.98：金事件（mythic）· 完成奖励稀有天级功法（寿元/气运/渡劫）——
  {band:3, q:'mythic', minAge:60, name:'寿元长生殿', text:'云海深处浮现一座上古丹殿，殿中丹香凝成寿桃之形——传说参透其中丹道，可窥寿元之秘。',
   opts:[{label:'入殿参悟', need:{attr:{悟性:48}}, artPool:['万寿丹经'], eff:{声望:10, 神识:4}, txt:'殿中丹经自燃成辉，你捕捉到一丝长生真意，道基中寿元暗长。'}, {label:'敬而远之', eff:{悟性:2}, txt:'神物有灵，你躬身而退。'}]},
  {band:3, q:'mythic', minAge:70, name:'天机星陨', text:'一颗古星坠于大泽，星核内流转着天人合一的推演法门，传闻得之可夺天地气运一线。',
   opts:[{label:'参悟星核', need:{attr:{悟性:52}}, artPool:['天机气运诀'], eff:{声望:8, 神识:5}, txt:'星辉入识，你望见命运长河的涟漪，气运为之加身。'}, {label:'将星核献于宗门', eff:{贡献:60}, txt:'你献上星核，宗门震动。'}]},
  {band:3, q:'mythic', minAge:80, name:'雷池悟道', text:'渡劫古地中央雷池翻涌，池畔石碑刻满前人渡劫感悟——若能参透，天劫亦可轻渡。',
   opts:[{label:'盘坐雷池畔', need:{attr:{悟性:55}}, artPool:['渡厄真经'], eff:{声望:10, 神识:6}, txt:'雷声入耳化作经文，你参透渡厄之秘，对天劫的畏惧烟消云散。'}, {label:'隔岸观望', eff:{悟性:3}, txt:'雷威骇人，你远远观摩片刻离去。'}]},
  // —— XL_RS 4.120：金事件（mythic）· 洗髓丹——洗去灵根一个属性（仅双灵根及以下：双→天、三→双、四→三、杂→四）——
  {band:3, q:'mythic', minAge:60, once:true, req:{qualityIn:['pu','you','ding','super']}, name:'洗髓丹',
   text:'上古丹方在你识海深处浮现——洗髓丹可洗去灵根中的一缕杂质，令资质返本归元。你耗费三载寻齐诸般灵药，丹成之日霞光万道，异香满室……',
   opts:[{label:'服下洗髓丹', xiSui:true, eff:{神识:5, 悟性:3}, txt:'丹药入腹，一股清凉自丹田涌遍四肢百骸……'}, {label:'留待日后', eff:{悟性:2}, txt:'神物不可轻用，你将丹方仔细收好，待来日再议。'}]},
  // ==================== XL_RS 4.130：事件库扩充（补品质×年龄段缺口） ====================
  // 幼年（b0）紫品——此前 b0 无任何 epic 事件
  {band:0, q:'epic', minAge:8, name:'祖传玉简', once:true, text:'家中翻出一枚祖传玉简，据说是百年前一位筑基先祖所留。觉醒之夜，玉简表面竟泛起幽光，与你的灵根隐隐共鸣。',
   opts:[{label:'滴血认主', need:{attr:{悟性:12}}, roll:{chance:0.55, succ:{悟性:4, 气运:2, 神识:2}, succText:'玉简光华大放，先祖的修行感悟灌顶而入——灵台清明，道基微固！', fail:{气血:-2}, failText:'玉简气息反噬，你气血翻涌，踉跄而退。'}}, {label:'转赠族中', eff:{家境:2, 声望:1}, txt:'你念及家族，将玉简留给后来人。'}]},
  // 少年（b1）金品——此前 b1 无任何 mythic 事件（先天道体，三灵根及以上方可触发，选项 2 经气运判定）
  {band:1, q:'mythic', minAge:14, name:'先天道体', once:true, req:{minQuality:'ding'}, text:'晨钟暮鼓间，你骤然觉得周天灵气亲和无比——这具身躯竟是传闻中的先天道体，与道相合，修行一日千里。',
   opts:[{label:'顺天应道', eff:{lv:2, 悟性:4}, txt:'先天道体与道亲和，你运转周天，修为一日千里！'}, {label:'求问天机', need:{attr:{气运:20}}, roll:{chance:0.4, succ:{气运:5, 悟性:3}, succText:'天机指引，你寻得一处灵脉，道体吞吐灵气事半功倍！', fail:{悟性:-1}, failText:'天机晦涩，你空耗数日，一无所获。'}}]},
  // 老年（b3）红品——上古遗府（渡劫期前后探索向）
  {band:3, q:'legend', minAge:70, name:'上古遗府', once:true, text:'云深之处，一座上古遗府自虚空浮现——门楣上一个「道」字流转不定，仿佛在等一个真正的有缘人。',
   opts:[{label:'入府探宝', need:{attr:{神识:45}}, roll:{chance:0.4, succ:{悟性:8, 神识:6, 气运:4}, succText:'你在遗府深处寻得前人遗蜕与道藏残篇，道心大进！', fail:{气血:-15}, failText:'遗府机关重重，你负伤退出。', death:0.1, deathText:'殒落于上古遗府'}}, {label:'过门不入', eff:{悟性:2}, txt:'你深知机缘与风险相伴，躬身而退。'}]},
  // 老年（b3）金品——大道残篇（奖励天级功法：寿元/气运/渡劫一类）
  {band:3, q:'mythic', minAge:78, name:'大道残篇', text:'断崖之上，一部残缺道经悬于半空，字字如星辰坠落——传闻参透者可窥见「道」的真容。',
   opts:[{label:'参悟残篇', need:{attr:{悟性:60}}, artPool:['万寿丹经','天机气运诀','渡厄真经'], eff:{声望:10, 神识:6}, txt:'残篇字迹化作星光没入识海，你窥见大道一隅，道心通明！'}, {label:'默记于心', eff:{悟性:4}, txt:'你强行记住几句残文，留待日后参详。'}]},
  // —— XL_RS 4.144：功德业力事件扩充（提高功德供给，让功德飞升门槛更易达到；邪路选项同步给业力）——
  {band:2, q:'rare', minAge:28, maxAge:60, name:'渡口无名骨', text:'江畔渡口，一具无名骸骨被潮水冲上滩涂，往来行人掩鼻而过，无人问津。',
   opts:[{label:'买棺安葬', eff:{功德:5, 灵石:-30}, txt:'你买来棺木将其入土为安，焚香三炷，愿你早入轮回。'}, {label:'视若无睹', eff:{业力:1}, txt:'世事纷扰，你匆匆赶路，将那一滩白骨抛在身后。'}]},
  {band:2, q:'epic', minAge:32, maxAge:60, name:'荒野活命恩', text:'荒野小径，一名采药人正被妖兽扑倒，血染衣襟，嘶声呼救。',
   opts:[{label:'出手相救', need:{attr:{力量:15}}, roll:{chance:0.6, succ:{功德:6, 声望:4}, succText:'你一剑逼退妖兽，采药人叩首谢恩，奉上珍藏药草。', fail:{气血:-8}, failText:'妖兽凶猛，你救人心切反被撕开一道血口。'}}, {label:'袖手旁观', eff:{业力:3}, txt:'多一事不如少一事，你绕道而行，身后惨叫声渐远。'}]},
  {band:2, q:'epic', minAge:40, maxAge:60, name:'疫村施药', text:'前方村落瘟疫横行，户户闭门，村口老翁跪地求药，声泪俱下。',
   opts:[{label:'散财购药赈灾', eff:{功德:9, 声望:6, 灵石:-80}, txt:'你购来丹方药材分施全村，七日之后疫气渐散，万民称颂。'}, {label:'囤药待价而沽', eff:{业力:5, 灵石:100}, txt:'你暗中囤下药材，等疫情蔓延，再抬价出售。'}]},
  {band:3, q:'epic', minAge:60, maxAge:110, name:'怨魂托梦', text:'夜半时分，一孤魂入梦，诉说生前冤屈，求你了却遗愿。',
   opts:[{label:'以神识超度', need:{attr:{神识:25}}, eff:{功德:8, 神识:3}, txt:'你诵经七日，超度孤魂往生，眉心戾气尽散。'}, {label:'借怨力炼法', eff:{业力:4, 神识:5}, txt:'你炼化其怨气为神识养料，孤魂消散前凄厉长啸。'}]},
  {band:3, q:'legend', minAge:65, maxAge:110, name:'古刹修缮', text:'深山古刹年久失修，梁柱朽蚀，僧众下山化缘却屡屡碰壁。',
   opts:[{label:'捐资重修', eff:{功德:10, 气运:2, 灵石:-150}, txt:'你捐出大笔灵石重修古刹，佛像金身再塑，香火重燃。'}, {label:'取走殿中古钟', eff:{业力:6, 灵石:120}, txt:'你趁夜盗走古钟熔炼，寺中钟声自此断绝。'}]},
  {band:3, q:'legend', minAge:70, maxAge:110, name:'旱灾开仓', text:'大旱三年，赤地千里，官府粮仓紧闭，流民哀鸿遍野。',
   opts:[{label:'开仓赈灾', need:{attr:{声望:20}}, eff:{功德:12, 声望:8}, txt:'你打开粮仓放粮赈济，百姓跪谢活命之恩，青史留名。'}, {label:'趁乱囤积', eff:{业力:8, 灵石:150}, txt:'你趁乱低价收购田产，囤粮待涨，嘴角泛起冷笑。'}]},
  // —— XL_RS 4.148：道侣羁绊事件链（req spouse；bond 双修成长/事件增减，渡劫加成上限+5%）——
  {band:2, q:'rare', minAge:25, maxAge:130, req:{spouse:true}, name:'道侣遇险', text:'一行魔修拦住去路，你的道侣为护你身陷重围，血染衣襟。',
   opts:[{label:'拼死相救', need:{attr:{力量:20}}, roll:{chance:0.65, succ:{bond:8, 气血:3}, succText:'你杀透重围，将道侣护在身后，生死之间羁绊愈深。', fail:{bond:-4, 气血:-5}, failText:'敌手太强，你们且战且退双双负伤，道侣眼中却更添坚定。'}}, {label:'传讯求援', eff:{bond:-6, 悟性:1}, txt:'你强忍心悸传讯求援，道侣虽脱险，却因此事生了隔阂。'}]},
  {band:2, q:'rare', minAge:25, maxAge:130, req:{spouse:true}, name:'共赴秘境', text:'坊间传闻一处上古秘境开启，你的道侣兴致勃勃，邀你同行。',
   opts:[{label:'携手同往', roll:{chance:0.6, succ:{bond:5, 灵石:120}, succText:'秘境中二人配合无间，寻得前人遗藏，满载而归。', fail:{bond:2, 悟性:1}, failText:'秘境凶险，你们空手而归，却也于生死间更懂彼此。'}}, {label:'独行探秘', eff:{bond:-3, 悟性:2}, txt:'你让{ta}留守，独自深入——收获虽丰，{ta}眼中却多了一丝疏离。'}]},
  {band:2, q:'rare', minAge:30, maxAge:120, req:{spouse:true}, name:'道侣赠礼', text:'你的道侣闭关数月，出关时郑重将一件贴身之物递到你手中。',
   opts:[{label:'欣然收下', roll:{chance:0.5, succ:{bond:4, 悟性:1}, succText:'{ta}抿唇一笑，眉眼弯弯，这份心意比法宝更珍贵。', fail:{bond:2}, failText:'你郑重收下，心中暖流涌动。'}}, {label:'婉言推辞', eff:{bond:1, 悟性:1}, txt:'你道心意已领，不必费心——{ta}愣了愣，欲言又止。'}]},
  {band:3, q:'rare', minAge:60, maxAge:200, req:{spouse:true}, name:'道侣离心', text:'这些年聚少离多，你的道侣望着你的背影欲言又止——有些话，{ta}终于说了出来。', once:true,
   opts:[{label:'剖白心迹，极力挽留', roll:{chance:0.5, succ:{bond:6, 悟性:1}, succText:'长夜倾谈，心结尽解，{ta}重又依偎在你身侧。', fail:{spouseLost:true}, failText:'{ta}摇了摇头，留下决绝的背影，从此两不相欠。'}}, {label:'沉默以对，随{ta}去吧', eff:{spouseLost:true, 悟性:2}, txt:'你未发一言。次日{ta}已离去，只留下一句「道不同，不相为谋」。'}]},
  {band:3, q:'epic', minAge:90, maxAge:250, req:{spouse:true}, name:'凡缘终尽', text:'暮色沉沉，你的道侣垂垂老矣，握着你手，气若游丝：「能陪你走到这里，我这一生，值了。」', once:true,
   opts:[{label:'相伴终老，送{ta}最后一程', roll:{chance:0.5, succ:{spouseLost:true, 悟性:3, 神识:3}, succText:'{ta}含笑而去。你静坐七日，一朝悟道，心境圆融——生离死别，原是修行。', fail:{spouseLost:true, 气血:-2, 悟性:1}, failText:'{ta}走了。你泣不成声，数日难以自持，唯余心口钝痛。'}}, {label:'倾尽家财，求灵药续命', need:{money:500}, roll:{chance:0.5, succ:{bond:8, 灵石:-500}, succText:'天材地宝入腹，{ta}竟缓缓回神，又多伴你十年——这十年，千金不换。', fail:{spouseLost:true, 灵石:-500, 气血:-3}, failText:'灵药终究难逆天命，{ta}去了。人财两空，你大病一场。'}}]},
  // XL_RS 4.151：子嗣成长事件（req hasChild，接现有品质池）
  {band:2, q:'rare', minAge:30, maxAge:110, req:{hasChild:true}, name:'子嗣拜师', text:'有高人路过，看中你的子嗣根骨，欲收为弟子。',
   opts:[{label:'应允拜师', need:{attr:{声望:20}}, roll:{chance:0.6, succ:{kidDao:20, 声望:6}, succText:'子嗣拜入高人门下，道基大进，日后必有大出息。', fail:{kidDao:8, 声望:2}, failText:'高人言子嗣缘法未到，拂袖而去，只留下几句点拨。'}}, {label:'留子身边亲自教导', eff:{kidDao:5, 悟性:1}, txt:'你亲自教导，父子情谊更深，道基亦有进益。'}]},
  {band:2, q:'rare', minAge:35, maxAge:115, req:{hasChild:true}, name:'子嗣遇险', text:'你的子嗣外出历练，身陷险境，命悬一线。',
   opts:[{label:'亲赴救援', need:{attr:{力量:30}}, roll:{chance:0.6, succ:{kidDao:15, 声望:5}, succText:'你及时赶到，救下子嗣——经此一役，子嗣心性更坚，道基渐厚。', fail:{声望:-3, 气血:-3}, failText:'你还是慢了一步，子嗣重伤，你心痛难当。'}}, {label:'传讯安抚，静观其变', eff:{声望:-1}, txt:'你按捺住心焦，子嗣终靠自己脱险，历练有成。'}]},
  {band:3, q:'uncommon', minAge:45, maxAge:140, req:{hasChild:true}, name:'子嗣成家', text:'你的子嗣到了成家的年纪，前来询问你的意思。',
   opts:[{label:'操持婚事', need:{money:200}, eff:{家境:5, 声望:3}, txt:'你为子嗣风光操办婚事，家族人丁更旺。'}, {label:'一切从简', eff:{声望:1}, txt:'简朴成婚，子嗣知你务实，反而更加敬重。'}]},
  // ============ DL_RS_4.154 仇敌系统 ============
  {band:1, q:'rare', minAge:15, name:'古墓夺宝', text:'你在古修洞府与同道狭路相逢，为一桩传承法器互不相让。', w:0.4,
   opts:[{label:'强取豪夺', eff:{enemyAdd:1, 悟性:3}, txt:'你出手夺下法器，对方怀恨在心。'}, {label:'拱手相让', eff:{气运:2}, txt:'你大方相让，结个善缘。'}]},
  {band:2, q:'rare', minAge:35, name:'灭门旧怨', text:'一伙魔修屠戮青阳镇，你出手救下遗孤，为首魔修记下了你的面容。', w:0.4,
   opts:[{label:'仗义出手', eff:{enemyAdd:1, 声望:8}, txt:'你救下遗孤，却也与魔修结下死仇。'}, {label:'明哲保身', eff:{声望:-3}, txt:'你袖手旁观，心绪难平。'}]},
  {band:3, q:'rare', minAge:60, name:'道统之争', text:'你讲道论法锋芒毕露，一方势力视你为道统大敌，放出风声要清算于你。', w:0.4,
   opts:[{label:'正面交锋', eff:{enemyAdd:1, 声望:10}, txt:'你当众驳斥对方，结下仇怨。'}, {label:'示弱求和', eff:{声望:-5}, txt:'你主动示弱，暂避锋芒。'}]},
  {band:1, q:'rare', minAge:16, req:{enemy:true}, type:'enemy', name:'仇家寻仇', text:'年少结怨之人寻上门来，誓要讨个说法。', w:0.6,
   opts:[{label:'正面对决', _act:'fight', duelTxt:'道行检验，胜者生、败者伤'}, {label:'破财消灾', _act:'pay', duelTxt:'以灵石了结恩怨'}, {label:'以德报怨', _act:'mercy', duelTxt:'净功德≥100 可感化仇敌'}, {label:'避而不见', _act:'flee', duelTxt:'声望-3，仇敌气焰更盛'}]},
  {band:2, q:'rare', minAge:31, req:{enemy:true}, type:'enemy', name:'仇敌寻仇', text:'你的仇家纠集人手，趁你闭关松动之际发难。', w:0.6,
   opts:[{label:'正面对决', _act:'fight', duelTxt:'道行检验，胜者生、败者伤'}, {label:'破财消灾', _act:'pay', duelTxt:'以灵石了结恩怨'}, {label:'以德报怨', _act:'mercy', duelTxt:'净功德≥100 可感化仇敌'}, {label:'避而不见', _act:'flee', duelTxt:'声望-3，仇敌气焰更盛'}]},
  {band:3, q:'rare', minAge:61, req:{enemy:true}, type:'enemy', name:'旧怨爆发', text:'积年旧怨一朝爆发，仇家亲至，杀气盈野。', w:0.6,
   opts:[{label:'正面对决', _act:'fight', duelTxt:'道行检验，胜者生、败者伤'}, {label:'破财消灾', _act:'pay', duelTxt:'以灵石了结恩怨'}, {label:'以德报怨', _act:'mercy', duelTxt:'净功德≥100 可感化仇敌'}, {label:'避而不见', _act:'flee', duelTxt:'声望-3，仇敌气焰更盛'}]},
  // ============ DL_RS_4.155 宗门晋升线 ============
  {band:2, q:'rare', minAge:35, req:{hasOrg:true}, name:'宗门擢升', text:'你在宗门中崭露头角，掌门钦点你为真传弟子，前途可期。', w:0.35,
   opts:[{label:'应下擢升', eff:{promote:'真传', 声望:5}, txt:'你荣任真传弟子，得以参悟更深传承。'}, {label:'婉言谢绝', eff:{贡献:50}, txt:'你推辞擢升，一心修行，宗门念你谦逊。'}]},
  {band:3, q:'epic', minAge:71, req:{hasOrg:true, gongxian:8000, lv:71}, name:'掌门之争', text:'宗门长老会一致推举你继任掌门——你修为冠绝宗门，威望无人能及。', w:0.5,
   opts:[{label:'继位登临', eff:{promote:'掌门', 声望:20}, txt:'你登临掌门之位，执掌一宗气运。'}, {label:'让贤推辞', eff:{贡献:800, 声望:10}, txt:'你淡泊名利，推举贤能，宗门上下敬你高风亮节。'}]},
  /* ==== DL_RS_4.164 宗门深化：任务/镇守/掌门决策 ==== */
  {band:2, q:'common', minAge:25, req:{hasOrg:true}, name:'宗门任务·炼丹采药', text:'丹房缺一炉清心丹的灵药，长老吩咐你入山采药——宗门上下都看着这炉丹成。', w:1.0,
   opts:[{label:'采药交宗', eff:{贡献:80, 灵石:30}, txt:'灵药归宗，丹炉生辉，长老点头赞许。'}, {label:'私留灵药', eff:{灵石:60, 贡献:-40}, txt:'你悄悄扣下几株灵药换作灵石，此事瞒不过有心人。'}]},
  {band:2, q:'uncommon', minAge:30, req:{hasOrg:true}, name:'宗门任务·护送商队', text:'宗门商队要押一批灵材过青岩岭，长老点了你的名——这一路山高林密，恐有劫修出没。', w:0.8,
   opts:[{label:'护送商队', roll:{chance:0.9, succ:{贡献:110, 灵石:50, 声望:3}, succText:'商队安然抵达，你出手击退小股劫修，宗门记你一功。', fail:{贡献:40, 气血:-10}, failText:'商队遇袭，你力战护住货物，带伤回宗。'}}, {label:'称病推脱', eff:{贡献:-30}, txt:'你推脱了差事，长老虽未说什么，目光却冷了几分。'}]},
  {band:2, q:'uncommon', minAge:35, req:{hasOrg:true}, name:'宗门任务·除妖净域', text:'宗门辖下的黑风岭有妖物伤人，掌门命你带人清剿——斩妖除魔，正是扬名立威之时。', w:0.7,
   opts:[{label:'拔剑斩妖', roll:{chance:0.65, succ:{贡献:120, 声望:5}, succText:'妖物授首，黑风岭重归安宁，你的名号传遍宗门。', fail:{气血:-15}, failText:'妖物凶悍，你负伤败退，回宗疗养。'}}, {label:'借故避让', eff:{贡献:-30}, txt:'你推说伤势未愈避过了差事，宗门上下议论纷纷。'}]},
  {band:3, q:'uncommon', minAge:50, req:{hasOrg:true}, name:'宗门任务·镇守矿脉', text:'宗门灵矿脉近日异动频繁，疑似有妖修觊觎，长老命你坐镇矿场三月。', w:0.6,
   opts:[{label:'尽职镇守', eff:{贡献:150, 灵石:80}, txt:'矿脉安稳，宗门论功行赏。'}, {label:'监守自盗', eff:{灵石:150, 贡献:-60}, txt:'你中饱私囊之事被巡查长老撞破，颜面扫地。'}]},
  {band:3, q:'rare', minAge:55, req:{hasOrg:true}, name:'宗门镇守战·魔道来袭', text:'北境魔道大举来犯，兵锋直指宗门山门——护山大阵告急，宗门召唤所有修士共御外敌！', w:0.35,
   opts:[{label:'披甲迎战', roll:{chance:0.6, succ:{贡献:500, 声望:12, 悟性:3}, succText:'你在山门血战中大显神威，斩魔道长老于阵前，宗门上下奉为英雄！', fail:{气血:-20, 贡献:-80}, failText:'魔道势大，你浴血奋战仍不敌，身负重伤退回宗门。'}}, {label:'避战不出', eff:{贡献:-100, 声望:-5}, txt:'你闭关不出，战后宗门追责，威信扫地。'}]},
  {band:3, q:'epic', minAge:71, req:{hasOrg:true, post:'掌门'}, name:'掌门决策·宗门兴衰', text:'你执掌宗门，一道关乎宗门百年气运的抉择摆在案前——进则开疆拓土，退则守成养望，皆有得失。', w:0.4,
   opts:[{label:'开疆拓土', eff:{贡献:-2000, 声望:20, 悟性:3}, txt:'你挥师东进，连破三处灵脉，宗门疆域大张，威名远播。'}, {label:'广纳贤才', eff:{灵石:-500, 贡献:500}, txt:'你广开山门，招揽散修英才，宗门实力大增。'}, {label:'闭门修整', eff:{lv:1}, txt:'你下令封山修整，宗门上下潜心修炼，你也闭关数月，修为精进。'}]},
  /* ==== 事件链·古修洞府（XL_RS 4.165 洞府/秘境探索：破禁入府→甬道二择→主室探宝→传承收尾） ==== */
  {band:2, q:'epic', minAge:40, maxAge:85, name:'古修洞府', text:'一处荒山野岭灵气异常流转——竟是座被阵法遮蔽的上古修士洞府。禁制微光流转，石门半掩，机缘与凶险同藏其中。', once:true, chainId:'dongfu', chainStart:true, step:'df1', w:0.28,
   opts:[{label:'以神识破阵', need:{attr:{神识:30}}, roll:{chance:0.7, extra:0.05, succ:{}, succText:'你以神识顺藤摸瓜，阵眼应声而破，石门轰然洞开。', fail:{气血:-10}, failText:'阵法反噬，你闷哼受轻伤，仍强挤入洞。'}, chainGoto:'df2'}, {label:'以力强攻禁制', need:{attr:{力量:30}}, roll:{chance:0.5, extra:0.05, succ:{}, succText:'你拳掌齐出，硬生生轰开禁制一角。', fail:{气血:-20}, failText:'禁制爆裂，你被震得气血翻涌。'}, chainGoto:'df2'}, {label:'谨慎离去', eff:{}, chainEnd:true}]},
  {band:2, q:'epic', name:'洞府前厅', text:'前厅空荡古朴，两侧各通一条甬道——左道灵光隐隐，右道阴风阵阵，深处似有重宝气息。', chainId:'dongfu', step:'df2',
   opts:[{label:'走左道（灵光）', roll:{chance:0.7, extra:0.05, succ:{灵石:500}, succText:'甬道尽头一间小石室，盛着一箱灵晶，灵石 +500。', fail:{气血:-8}, failText:'灵光原为幻阵虚影，你误触禁制被震退。'}, chainGoto:'df3'}, {label:'走右道（阴风）', roll:{chance:0.5, extra:0.05, succ:{灵石:300}, succText:'阴风尽头散落灵石与几枚玉简，灵石 +300。', fail:{气血:-15}, failText:'阴风骤起如刀，你添了几道伤口。'}, chainGoto:'df3'}, {label:'原路退回', eff:{}, chainEnd:true}]},
  {band:2, q:'epic', name:'洞府主室', text:'主室正中一座石台，台上悬着一件灵光四溢的宝物，旁置一只玉瓶、一卷玉简。', chainId:'dongfu', step:'df3',
   opts:[{label:'取下宝物', roll:{chance:0.6, extra:0.05, succ:{灵石:400}, succText:'宝物入手——竟是一件难得的灵器！石台旁散落的灵石也被你收起，灵石 +400。', fail:{气血:-12}, failText:'宝物下有机关，毒针激射，你伤得不轻，宝物亦碎。'}, bone:'灵器', chainGoto:'df4'}, {label:'只取玉瓶丹药', roll:{chance:0.8, extra:0.05, succ:{悟性:3, 气血:3}, succText:'玉瓶中盛着上古淬体丹，药力入体，悟性 +3、气血 +3。', fail:{}, failText:'丹药年久失效，空欢喜一场。'}, chainGoto:'df4'}, {label:'不贪，原路退出', eff:{}, chainEnd:true}]},
  {band:2, q:'epic', name:'传承石碑', text:'密室中央青石碑下压着一枚传承玉简，录有一门上古养生功法——青木长生功，与你气机隐隐相合。', chainId:'dongfu', step:'df4', chainEnd:true, art:'青木长生功',
   opts:[{label:'参悟碑文', roll:{chance:0.5, extra:0.05, succ:{悟性:2}, succText:'碑文真意入心，你对木系养生的理解更深一层，悟性 +2。', fail:{神识:-5}, failText:'碑文晦涩如渊，强参之下神识受损。'}}, {label:'收起玉简，离开', eff:{}}]},
  /* ==== 秘境宝库（XL_RS 4.165：限时秘境，三层探索风险递进） ==== */
  {band:2, q:'epic', minAge:45, maxAge:95, name:'秘境宝库·现世', text:'南海灵潮暴涨，一座上古秘境宝库裂开门户，灵光冲天——各方修士闻讯涌入，宝库三日后封闭。', once:true, w:0.3,
   opts:[{label:'表层探宝', roll:{chance:0.9, extra:0.05, succ:{灵石:300, 悟性:1}, succText:'你在秘境边缘拾获灵石与灵草，灵石 +300、悟性 +1。', fail:{气血:-5}, failText:'边缘亦有禁制，你被扫了一记。'}}, {label:'中层探秘', roll:{chance:0.65, extra:0.05, succ:{灵石:500}, succText:'中层石廊中你寻得一柄灵器与一袋灵石，灵石 +500。', fail:{气血:-15}, failText:'中层机关重重，你负伤遁出。'}, bone:'灵器'}, {label:'直取核心', roll:{chance:0.35, extra:0.05, succ:{灵石:800}, succText:'你硬闯核心宝殿，夺得一件宝器与满箱灵石，灵石 +800！', fail:{气血:-30}, failText:'核心殿内化神级禁制爆发，你重伤退出，险些殒命。'}, bone:'宝器'}]},

  /* ==== 道侣专属事件（XL_RS 4.170：模块四——triggerEvent 钩子区独立触发；_manual 排除出品质池） ==== */
  {band:2, q:'legend', spouseEv:true, _manual:true, name:'结缘纪念', text:'恰逢你与道侣结缘百载之期。山门外的旧桃树又开花了，{ta}在树下回首望你，目光温软。',
   opts:[
     {label:'共度纪念，温酒长谈', eff:{bond:1, 悟性:1}, txt:'你们于旧桃树下温酒对酌，说尽百年风霜。羁绊+1、悟性+1。'},
     {label:'筹备一场惊喜', need:{money:100}, eff:{bond:3, 灵石:-100}, txt:'你费心备下灵宴与信物，{ta}眼角眉梢都是笑意。羁绊+3。'}
   ]},
  {band:2, q:'legend', spouseEv:true, _manual:true, name:'道侣突破', text:'闭关多年的道侣功行圆满，气息鼓荡——{ta}欲破境而上，却还欠缺几分机缘。',
   opts:[
     {label:'为其护法，倾力相助', need:{money:200}, roll:{chance:0.6, extra:0.05, succ:{spouseLv:1, bond:5, 灵石:-200}, succText:'有你以道行护持，{ta}一举破境，境界再上一层！', fail:{bond:1, 灵石:-200}, failText:'这次突破差了些火候，{ta}功亏一篑，却对你愈发依赖。'}},
     {label:'赠一枚破境丹', need:{money:80}, eff:{bond:3, 灵石:-80}, txt:'丹药入腹，{ta}道行微进，笑意温存。羁绊+3。'},
     {label:'言语宽慰', eff:{bond:1}, txt:'你言修行不必急于一时，{ta}心中稍安。羁绊+1。'}
   ]},
  {band:2, q:'legend', spouseEv:true, _manual:true, name:'道侣闭关', text:'你的道侣道行将进，需闭关参悟。临行前，{ta}将闭关之所托付于你。',
   opts:[
     {label:'亲自护关', eff:{bond:3, 悟性:1}, txt:'你在洞府外静坐守关百余日，道心亦有所得。羁绊+3、悟性+1。'},
     {label:'任其自行', eff:{bond:-2}, txt:'{ta}出关时见你不在，眼底掠过一丝落寞。羁绊-2。'}
   ]},
  {band:2, q:'legend', spouseEv:true, _manual:true, needBond:60, name:'误会风波', text:'近来风言风语传进道侣耳中，{ta}望着你欲言又止，眼底有藏不住的委屈与猜疑。',
   opts:[
     {label:'坦诚解释，剖白心意', roll:{chance:0.65, extra:0.05, succ:{bond:3, 悟性:1}, succText:'你坦然相告，心结尽释，{ta}破涕为笑。', fail:{bond:-4}, failText:'你越解释{ta}越觉你遮掩，冷着脸拂袖而去。'}},
     {label:'以沉默处之', eff:{bond:-3}, txt:'你不置一词，{ta}的眉眼一点点冷了下去。羁绊-3。'},
     {label:'携礼赔罪', need:{money:60}, eff:{bond:2, 灵石:-60}, txt:'你寻来{ta}惦记已久的灵物相赠，二人重归于好。羁绊+2。'}
   ]},
  {band:2, q:'legend', spouseEv:true, _manual:true, name:'论道共参', text:'夜深人静，道侣叩门而来，持一卷上古残经，邀你同参大道。',
   opts:[
     {label:'畅谈大道，印证所学', eff:{bond:2, 悟性:2}, txt:'二人彻夜论道，于残经中窥见一线道机。羁绊+2、悟性+2。'},
     {label:'倾囊指点', eff:{bond:1, spouseLv:1}, txt:'你将自己所悟倾囊相授，{ta}茅塞顿开，境界更进一步。羁绊+1、道侣境界+1。'}
   ]},
  {band:2, q:'legend', spouseEv:true, _manual:true, name:'道侣重伤', text:'道侣外出除妖归来，浑身浴血，气息奄奄——{ta}强撑着对你笑了笑：「无碍，皮外伤。」',
   opts:[
     {label:'悉心照料，寸步不离', eff:{bond:4, 气血:-3}, txt:'你日夜照料，耗尽心神为{ta}疗伤。羁绊+4，你气血-3。'},
     {label:'重金求购疗伤圣药', need:{money:120}, eff:{bond:2, 灵石:-120}, txt:'灵药入腹，{ta}伤势大好，望向你的目光柔得化不开。羁绊+2。'},
     {label:'托付医馆照料', need:{money:40}, eff:{bond:1, 灵石:-40}, txt:'医馆回春妙手，{ta}伤势渐愈，只是怨你不够上心。羁绊+1。'}
   ]},

  /* ==== 坊市奇遇事件（XL_RS 4.172：doAction('逛坊市') 30% 触发；marketEv + _manual 排除品质池） ==== */
  {band:2, q:'rare', marketEv:true, _manual:true, name:'坊市捡漏', text:'你在坊市地摊间闲逛，忽见一摊主将件旧物随手丢在角落。你定睛一看——那物灵气内蕴，绝非凡品！',
   opts:[
     {label:'花费灵石买下', need:{money:50}, roll:{chance:0.55, extra:0.05, succ:{悟性:2, 气运:1}, succText:'你以低价购得灵物，回去细察竟暗藏玄机——悟性+2、气运+1！', fail:{灵石:-50}, failText:'你花 50 灵石买下旧物，回家一看竟真是旧物——钱财两空。'}},
     {label:'观望离开', txt:'你多看了两眼，终究没有出手。'}
   ]},
  {band:2, q:'epic', marketEv:true, _manual:true, name:'坊市残卷', text:'书肆角落里压着一卷泛黄残卷，店家只当废纸。你翻开两页，竟见上古道韵流转，似是一门失传功法的残篇。',
   opts:[
     {label:'参悟残卷', need:{money:80}, roll:{chance:0.6, extra:0.05, succ:{悟性:3}, succText:'你于残卷中窥见一线道机，悟性+3！', fail:{灵石:-80}, failText:'残卷晦涩难解，你耗神良久仍无所获，只赔了 80 灵石。'}},
     {label:'放弃', txt:'残卷真假难辨，你摇摇头放下。'}
   ]},
  {band:2, q:'common', marketEv:true, _manual:true, name:'黑商陷阱', text:'一个满脸堆笑的摊主拉着你，吹嘘手中的"万年灵参"如何如何。你瞥见他袖中藏着的秤砣，心知有诈。',
   opts:[
     {label:'当众识破', roll:{chance:0.6, extra:0.05, succ:{灵石:80}, succText:'你揭穿他的把戏，黑商灰溜溜赔了你 80 灵石息事宁人！', fail:{灵石:-100}, failText:'你上前理论反被倒打一耙，围观者哄笑，你只得破财 100 灵石。'}},
     {label:'绕开而行', txt:'多一事不如少一事，你转身绕开。'}
   ]},
  {band:2, q:'common', marketEv:true, _manual:true, name:'熟人摊主', text:'常年在坊市摆摊的旧识见到你，热情招呼：「道友来得巧，新到了一批好货，给你算便宜些！」',
   opts:[
     {label:'购置灵宝', need:{money:200}, eff:{气血:3, 悟性:1, 灵石:-200}, txt:'你挑了件趁手的灵宝，气血+3、悟性+1。'},
     {label:'品茶闲谈', need:{money:10}, eff:{悟性:1, 灵石:-10}, txt:'你与摊主饮茶闲谈半日，听他讲了些修行见闻，悟性+1。'}
   ]},
  {band:2, q:'legend', marketEv:true, _manual:true, name:'小拍卖会', text:'坊市今日举办小拍卖会，压轴之物灵气逼人。围观众人窃窃私语，你手头灵石恰好够上一够。',
   opts:[
     {label:'竞价拍下', need:{money:300}, roll:{chance:0.5, extra:0.05, succ:{气运:1, 悟性:2}, succText:'你咬牙喊出高价，竟真拍下那件奇物——气运+1、悟性+2！', fail:{灵石:-300}, failText:'你一路加价，却在中途被神秘人截胡，白白耗费 300 灵石。'}},
     {label:'旁观不语', txt:'你按捺住心动，只作壁上观。'}
   ]},
  {band:2, q:'epic', marketEv:true, _manual:true, name:'神秘摊位', text:'坊市尽头不知何时多出一个灰袍老者摆的摊位，货架上蒙着薄尘，却隐隐透出宝光。他抬眼看你：「小友，可要一观？」',
   opts:[
     {label:'一探究竟', roll:{chance:0.55, extra:0.05, succ:{灵石:150, 悟性:1}, succText:'灰袍老者点头赞许，赠你一袋灵石与一句箴言——灵石+150、悟性+1！', fail:{灵石:-50}, failText:'你触动了摊上禁制，老者摇头叹息，你赔了 50 灵石才脱身。'}},
     {label:'转身离开', txt:'来历不明的摊子，还是离远些好。'}
   ]},

  /* ==== DL_RS 4.176 秘境事件（_secret 只由「探秘」行动触发，不入品质池） ==== */
  {_secret:true, _secLv:0, band:3, q:'rare', name:'灵草丰茂', text:'药谷深处灵雾氤氲，一片灵草在石缝间舒展翠叶。',
   opts:[{label:'细心采撷', eff:{herbs:2}, txt:'你小心翼翼连根采下两株灵草，收入囊中。'},
         {label:'贪多求快', roll:{chance:0.7, succ:{herbs:3}, succText:'你手疾眼快又抢下一株！', fail:{气血:-4}, failText:'动作太大惊动了守草妖兽，被撵出药谷。'}}]},
  {_secret:true, _secLv:0, band:3, q:'epic', name:'崖壁灵参', text:'悬崖缝隙间一株通体莹白的灵参探出叶片，少说有三百年药龄。',
   opts:[{label:'冒险摘取', roll:{chance:0.6, succ:{灵石:200, 悟性:1}, succText:'你攀上崖壁摘下灵参，卖给坊市得了 200 灵石。', fail:{气血:-10}, failText:'崖壁湿滑，你跌落谷底摔得不轻。'}},
         {label:'记下位置', txt:'你默默记下位置，转身离去。'}]},
  {_secret:true, _secLv:0, band:3, q:'rare', name:'小妖袭扰', text:'一只獠牙外露的野狼妖拦住去路，低吼着不让你靠近灵药。',
   opts:[{label:'正面搏杀', roll:{chance:0.75, succ:{灵石:60, 力量:1}, succText:'你三招毙敌，剥下妖皮兽骨换得 60 灵石。', fail:{气血:-8}, failText:'野狼妖凶猛异常，你负伤而退。'}},
         {label:'绕路而行', txt:'多一事不如少一事，你绕道离开。'}]},
  {_secret:true, _secLv:0, band:3, q:'common', name:'迷途空返', text:'药谷中雾气越来越浓，你转了几圈又回到原地。',
   opts:[{label:'循迹原路返回', txt:'白白耗去一日，两手空空。'},
         {label:'耐心辨向', eff:{悟性:1}, txt:'你静心观察草木朝向，辨明归途——虽无收获，却悟得一丝辨路心得。'}]},
  {_secret:true, _secLv:1020, band:3, q:'epic', name:'猎得妖丹', text:'你伏击了一头落单的妖兽，剖腹取出一枚圆润妖丹。',
   opts:[{label:'收入囊中', eff:{灵石:300, materials:1}, txt:'妖丹与兽骨俱归你手，坊市必能卖出好价。'},
         {label:'就地炼化', roll:{chance:0.6, succ:{气血:10, 力量:2}, succText:'妖力入体，气血翻涌间你更加强壮。', fail:{气血:-12}, failText:'妖力反噬，你吐血倒退。'}}]},
  {_secret:true, _secLv:1020, band:3, q:'rare', name:'古藤灵药', text:'一株灵药攀附在古藤上，根须深深扎入兽骨之中。',
   opts:[{label:'小心采摘', eff:{herbs:2, 悟性:1}, txt:'你连藤带药一并采下，收获颇丰。'},
         {label:'以药饲兽', roll:{chance:0.5, succ:{materials:2}, succText:'你把灵药抛给守护兽，趁它进食时顺走两副兽骨。', fail:{气血:-6}, failText:'妖兽识破了你的把戏，追得你狼狈逃窜。'}}]},
  {_secret:true, _secLv:1020, band:3, q:'epic', name:'兽潮围猎', text:'远处尘土飞扬，一群妖兽正朝这边狂奔而来！',
   opts:[{label:'迎头搏杀', roll:{chance:0.55, succ:{灵石:400, 力量:2}, succText:'你杀穿兽潮，浑身浴血却收获颇丰！', fail:{气血:-18, death:0.03}, failText:'兽潮汹涌，你被冲散踩伤，险死还生。'}},
         {label:'攀树躲避', txt:'你躲上高树，等兽潮过境才爬下来，白耗一日。'}]},
  {_secret:true, _secLv:1020, band:3, q:'legend', name:'落单妖王', text:'一头重伤垂死的妖兽之王倒在溪边，妖丹与灵血皆是至宝。',
   opts:[{label:'趁势取丹', roll:{chance:0.45, succ:{灵石:800, 气运:1}, succText:'你一刀剖开妖王胸腹，取了妖丹便走。', fail:{气血:-20, death:0.05}, failText:'妖王临死反扑，你被利爪贯穿胸口，重伤濒死。'}},
         {label:'为其疗伤', roll:{chance:0.5, succ:{功德:5, 悟性:2}, succText:'你以灵药救活妖王，它感激地蹭了蹭你的手，留下一缕妖气护你周全。', fail:{气血:-10}, failText:'妖王气息紊乱，你反被它的护体妖气震伤。'}}]},
  {_secret:true, _secLv:26520, band:3, q:'epic', name:'功法残卷', text:'遗迹石室的蒲团下，压着一卷残破的玉简。',
   opts:[{label:'参悟残卷', eff:{lv:8, 悟性:2}, txt:'你盘坐参悟，残卷奥义如醍醐灌顶，修为大进。'},
         {label:'转售坊市', eff:{灵石:500}, txt:'残卷残缺难修，你索性卖给了坊市。'}]},
  {_secret:true, _secLv:26520, band:3, q:'rare', name:'古宝残骸', text:'遗迹深处的祭坛上，散落着几件灵光黯淡的古宝残片。',
   opts:[{label:'悉数收走', eff:{灵石:600, materials:1}, txt:'残片炼化后尚有不少灵性，坊市收购价不低。'},
         {label:'祭坛参拜', roll:{chance:0.5, succ:{气运:1, 悟性:2}, succText:'你诚心参拜，祭坛竟传来一道暖流，似有遗泽加身。', fail:{业力:2}, failText:'祭坛散发阴冷气息，你隐隐感到一丝不适。'}}]},
  {_secret:true, _secLv:26520, band:3, q:'rare', name:'陷阱机关', text:'你脚下的石板忽然塌陷，四周嗡鸣声起——触发了遗迹禁制！',
   opts:[{label:'强行闯关', roll:{chance:0.6, succ:{灵石:300, 悟性:1}, succText:'你身形如电，在机关合拢前抢出宝匣。', fail:{气血:-20}, failText:'飞针石弩齐射，你重伤逃出。'}},
         {label:'原路退回', eff:{气血:-8}, txt:'你闪避不及，被流矢擦伤，只得退出遗迹。'}]},
  {_secret:true, _secLv:26520, band:3, q:'legend', name:'上古传承', text:'遗迹大殿中央，一具枯骨盘坐蒲团，身前玉简流光溢彩。',
   opts:[{label:'承接传承', roll:{chance:0.5, succ:{lv:10, 神识:3, 悟性:3}, succText:'传承灌顶而入，你恍惚间看到上古大能一生求道之影，道行大进！', fail:{业力:5, 气血:-15, death:0.04}, failText:'传承意志反噬，你神魂受创，险些道基崩溃。'}},
         {label:'躬身一礼退去', eff:{功德:3}, txt:'你恭恭敬敬拜了三拜，不愿强夺前人遗泽。'}]},
  {_secret:true, _secLv:664020, band:3, q:'legend', name:'仙器碎片', text:'战场废墟中，一块泛着仙光的碎片静静插在焦土里。',
   opts:[{label:'摄出碎片', roll:{chance:0.55, succ:{灵石:1500, 气运:1}, succText:'你以灵力包裹碎片取出，仙光流转，必是仙器残件！', fail:{气血:-20, 业力:3}, failText:'碎片骤然爆发仙威，你被震退数丈，口吐鲜血。'}},
         {label:'封存此地', txt:'仙器有主，强取不祥，你记下位置离去。'}]},
  {_secret:true, _secLv:664020, band:3, q:'legend', name:'战场传承', text:'一名陨落仙修的遗骸旁，有一道未散的意志残影。',
   opts:[{label:'聆听遗言', roll:{chance:0.6, succ:{lv:12, 神识:5, 悟性:4}, succText:'残影将毕生感悟凝成一道灵光渡入你识海，你屹立当场，气息节节攀升！', fail:{业力:6, 气血:-15}, failText:'残影蕴含死气，你被侵蚀经脉，踉跄而退。'}},
         {label:'为其收敛遗骸', eff:{功德:6}, txt:'你以灵力为仙修收敛遗骸，入土为安，冥冥中似有功德加身。'}]},
  {_secret:true, _secLv:664020, band:3, q:'epic', name:'心魔侵蚀', text:'战场煞气冲霄，你恍惚间看到无数战死者的怨念扑来。',
   opts:[{label:'凝神守心', roll:{chance:0.65, succ:{神识:3, 悟性:2}, succText:'你道心通明，将怨念炼化，神识愈发凝练。', fail:{业力:6, 气血:-12}, failText:'怨念入体，你杀意翻涌，险些迷失。'}},
         {label:'速离此地', txt:'此地不宜久留，你收敛心神撤出战场。'}]},
  {_secret:true, _secLv:664020, band:3, q:'legend', name:'魔修截杀', text:'一道血影拦在归路上——有魔修盯上了你身上的宝物！',
   opts:[{label:'正面迎战', roll:{chance:0.5, succ:{灵石:1800, 力量:5}, succText:'你击溃魔修，搜得他的储物袋，收获惊人！', fail:{气血:-25, death:0.06}, failText:'魔修手段诡异，你重伤遁走，险些命丧当场。'}},
         {label:'破财消灾', eff:{灵石:-300}, txt:'你丢出一袋灵石吸引注意，趁隙脱身。'}]},
]
